Aam-Digital/ndb-core

- README.md
- app/alerts/alert.service.ts
- app/app.component.ts
- app/database/database-manager.service.ts
- app/database/entity-mapper.service.ts
- app/database/pouch-database-manager.service.ts
- app/model/entity.ts
- app/user/login.component.ts
- app/user/session.service.ts
- app/user/user.ts
- index.html
- package.json
- typings.json
completes a large part of Login ( #3 )
also completes the work on `EntityMapperService` ( #1 ) and uses this.
> Login through local and remote database

- .travis.yml
- src/app/user/user.ts
source https://medium.com/from-the-couch/angular-2-with-travis-ci-922040e01937
(tries to) fix #50
> trying to fix travis config

- src/app/session/session.service.spec.ts
- src/app/user/user.spec.ts
- src/app/user/user.ts
> Fixed CryptoJS salt generation

- src/app/database/pouch-database-manager.service.ts
- src/app/entity/entity-mapper.service.ts
- src/app/session/login/login.component.ts
- src/app/user/user-account/user-account.component.ts
Todos in the source code are not the appropriate place to request features. I've removed them and created Github issues where necessary.
> Removed feature Todos from the source code.

- src/app/config/config.service.ts
moved the database to our actual domain aam-digital.com
> changed couchdb database url to new server

- src/app/app-config/app-config.model.ts
- src/app/app-config/app-config.module.ts
- src/app/app-config/app-config.ts
- src/app/app.module.ts
- src/app/database/database-manager.service.provider.ts
- src/app/database/pouch-database-manager.service.ts
- src/app/latest-changes/app-version/app-version.component.ts
- src/assets/config.json
> loading json config file rather than hard-coding settings in service

- src/app/children/child-details/child-details.component.html
- src/app/children/child-details/child-details.component.ts
- src/app/children/children-list/children-list.component.ts
Fixed Routing and Editing for ChildDetails
> Edit change

- package.json
- src/app/children/child-details/child-details.component.css
- src/app/children/child-details/child-details.component.html
- src/app/children/child-details/child-details.component.ts
- src/app/children/child.ts
- src/app/children/children-list/children-list.component.html
- src/app/children/children-list/children-list.component.scss
- src/app/children/children-list/children-list.component.ts
- src/app/children/children.module.ts
- src/app/children/children.service.ts
- src/app/children/notes/note.ts
- src/app/database/mock-database-manager.service.ts
Creating/Editing children works with the formular. IDs are made with the uniqID package.
> editing & creating children

- src/app/admin/backup.service.spec.ts
- src/app/alerts/alert.service.ts
- src/app/alerts/alert.ts
- src/app/database/database-manager.service.provider.ts
- src/app/database/database.module.ts
- src/app/database/pouch-database-manager.service.spec.ts
- src/app/database/pouch-database-manager.service.ts
- src/app/database/pouch-database.spec.ts
- src/app/database/pouch-database.ts
- src/app/ui/search/search.component.spec.ts
> all logging done through AlertService instead of console.log

- npm-shrinkwrap.json
- package.json
- src/app/children/attendance/attendance-block/attendance-block.component.html
- src/app/children/children-list/children-list.component.html
- src/app/children/children-list/children-list.component.spec.ts
- src/app/children/children-list/children-list.component.ts
- src/app/children/children.module.ts
- src/app/children/educational-material/educational-material.component.html
- src/app/children/educational-material/educational-material.component.ts
- src/app/children/educational-material/educational-material.ts
- src/app/entity/entity.ts
- src/app/ui-helper/entity-subrecord/entity-subrecord.component.html
small improvements for better usability
see commit messages below
> small UX improvements

- .gitignore
- src/app/children/child-block/child-block.component.html
- src/app/children/child-block/child-block.component.scss
- src/app/children/child-details/child-details.component.css
- src/app/children/child-details/child-details.component.html
- src/app/children/child.ts
> Individual child photos

- src/app/children/attendance/add-day-attendance/add-day-attendance.component.html
- src/app/children/attendance/add-day-attendance/add-day-attendance.component.spec.ts
- src/app/children/attendance/add-day-attendance/add-day-attendance.component.ts
- src/app/children/attendance/attendance-average-dashboard/attendance-average-dashboard.component.ts
- src/app/children/attendance/attendance-month.ts
- src/app/children/attendance/attendance-week-dashboard/attendance-week-dashboard.component.html
- src/app/children/attendance/attendance-week-dashboard/attendance-week-dashboard.component.scss
- src/app/children/attendance/attendance-week-dashboard/attendance-week-dashboard.component.ts
- src/app/children/attendance/child-attendance/child-attendance.component.html
- src/app/children/attendance/child-attendance/child-attendance.component.spec.ts
- src/app/children/attendance/child-attendance/child-attendance.component.ts
- src/app/children/child-details/child-details.component.html
- src/app/children/child-details/child-details.component.ts
- src/app/dashboard/dashboard/dashboard.component.html
- src/app/database/mock-database.ts
- src/assets/changelog.json
- src/assets/config.json
> Hotfixes for v2.4

- src/app/app.routing.ts
> Fixed the school routing

- src/app/children/children-list/children-list.component.html
- src/app/children/children-list/children-list.component.ts
see issue: #178
- [] 
some variable names didn't match between the .ts and html-file, resulting in an error. I simply renamed them.
> Children list fix

- src/app/children/children-list/children-list.component.html
- src/app/children/children-list/children-list.component.scss
- src/app/children/children-list/children-list.component.ts
- src/app/children/notes/notes-manager/notes-manager.component.html
- src/app/children/notes/notes-manager/notes-manager.component.scss
- src/app/schools/school-detail/school-detail.component.css
- src/app/schools/school-detail/school-detail.component.html
- src/app/schools/schools-list/schools-list.component.css
- src/app/schools/schools-list/schools-list.component.html
- src/styles.css
see issue: #174 
- [] 
I made various minor changes to the way lists are displayed in the children, school and note tab.
> Children list ui

- package.json
- tslint.json
see issue: #189 
This just changes configuration for linting.
> Cleanup lint

- src/app/children/children-list/children-list.component.ts
> Fix Back Navigation

- src/app/navigation/navigation/navigation.component.html
- src/app/sync-status/sync-status/sync-status.component.css
- src/app/sync-status/sync-status/sync-status.component.html
- src/app/ui/search/search.component.html
- src/app/ui/search/search.component.scss
- src/app/ui/search/search.component.spec.ts
- src/app/ui/search/search.component.ts
- src/app/ui/ui/ui.component.css
- src/app/ui/ui/ui.component.html
- src/app/ui/ui/ui.component.spec.ts
- src/app/ui/ui/ui.component.ts
see issue: #124 
- sidenav menu is now responsive
- hamburger button now in top menu and only visible on small screens
- sidenav on small screens as popover
- can't hide sidenav on big screens
- removed navigation controls in sidenav (use the ones in the browser!)
- implemented search bar for small screens
> Responsive side nav

- src/app/children/attendance/attendance-average-dashboard/attendance-average-dashboard.component.html
- src/app/children/attendance/attendance-warnings-dashboard/attendance-warnings-dashboard.component.html
- src/app/children/attendance/attendance-week-dashboard/attendance-week-dashboard.component.html
- src/app/children/child-block/child-block.component.html
- src/app/children/child-details/child-details.component.css
- src/app/children/child-details/child-details.component.html
- src/app/children/child-details/child-details.component.ts
- src/app/children/childSchoolRelation.ts
- src/app/children/children-count-dashboard/children-count-dashboard.component.html
- src/app/children/view-schools-component/edit-school-dialog/edit-school-dialog.component.html
- src/app/dashboard/dashboard/dashboard.component.scss
- src/app/dashboard/progress-dashboard/progress-dashboard.component.html
- src/app/schools/school-detail/school-detail.component.css
- src/app/schools/school-detail/school-detail.component.html
- src/app/schools/school-detail/school-detail.component.ts
- src/styles.css
Several small but important bug fixes.
> Hotfixes 2.5.1

- src/app/alerts/alert-display.ts
- src/app/alerts/alert.service.spec.ts
- src/app/alerts/alert.service.ts
- src/app/alerts/alert.ts
- src/app/alerts/alerts/alert.component.spec.ts
- src/app/children/child-block/child-block.component.html
- src/app/children/child-block/child-block.component.ts
- src/app/children/child-select/child-select.component.ts
- src/app/database/pouch-database.ts
> Fix dangling relations at Notes

- src/app/children/children-list/children-list.component.html
- src/app/children/children-list/children-list.component.ts
- src/app/schools/schools-list/schools-list.component.html
- src/app/ui-helper/entity-subrecord/entity-subrecord.component.ts
> Fx layout searchpanel

- src/app/children/children.service.spec.ts
We created some tests in the testing workshop that can also be merged on the master.
> Test for children service

- package-lock.json
- package.json
> Greenkeeper/webpack 4.34.0

- src/app/children/aser/aser.ts
- src/app/entity/db-decorators.ts
This targets issue #263.
The PR targets to remove the schemaline object and replace it with annotations that are more readable.
To look at an example go to the aser.ts file.
The concrete but very provisionally implementation can be found in the file db-decorators.ts but should not be seen as final.
> [WIP] Schema decorators

- src/app/children/health-checkup/health-check.ts
- src/app/children/health-checkup/health-checkup.component.ts
> BMI_Tracking

- src/app/children/health-checkup/health-check.ts
> BMI Highlighting

- src/app/children/aser/aser.component.ts
- src/app/children/attendance/child-attendance/child-attendance.component.ts
- src/app/children/educational-material/educational-material.component.ts
- src/app/children/health-checkup/health-checkup.component.ts
- src/app/children/notes/notes.component.ts
- src/app/ui-helper/entity-subrecord/column-description.ts
- src/app/ui-helper/entity-subrecord/entity-subrecord.component.html
- src/app/ui-helper/entity-subrecord/entity-subrecord.component.ts
> Make BMI fields in HealthCheckup readonly

- src/app/children/attendance/attendance-month.ts
> fix(attendance): fix date type conversion problem causing errors

- README.md
- package-lock.json
- package.json
- proxy.conf.json
- src/assets/config.default.json
This will automatically proxy calls to from the dev-server to the demo backend, thus mitigating CORS issues.
Keep in mind that any non-default config.jsons must be updated as well to use the proxy.
Details on the proxy configuration can be found in the webpack docs: https://webpack.js.org/configuration/dev-server/#devserverproxy
> Add a proxy server to mitigate future CORS issues

- src/app/children/attendance/add-day-attendance/add-day-attendance.component.ts
see #369 
order roll call children by schoolClass.
> hotfix(add-day-attendance): enforce roll call ordered by children's class

- src/app/session/login/login.component.html
> Also allow to perform login() with enter if user-field is currently selected

- src/app/children/children-list/children-list.component.ts
- src/app/schools/schools-list/schools-list.component.ts
- src/app/ui/ui/ui.component.css
see issue: #326 
`ngOnInit` does not create media that are empty for the filter selection any more.
> Do not create empty media filters in school list

- src/app/children/child-select/child-select.component.html
- src/app/children/notes/note-details/note-details.component.html
- src/app/children/notes/note-details/note-details.component.scss
> change layout of note-details

- src/app/children/attendance/attendance-days/attendance-days.component.scss
- src/app/children/attendance/attendance-week-dashboard/attendance-week-dashboard.component.html
- src/app/children/attendance/attendance-week-dashboard/attendance-week-dashboard.component.scss
- src/app/children/children-count-dashboard/children-count-dashboard.component.scss
- src/app/dashboard/dashboard/dashboard.component.html
- src/app/session/login/login.component.html
- src/styles.css
some minor UI improvements (see commit messages)
> Minor ui fixes

- src/app/core/alerts/alerts/alert.component.css
- src/app/core/alerts/alerts/alert.component.html
- src/styles.css
> fix broken alert styling

- package-lock.json
- package.json
- src/app/child-dev-project/children/select-group-children/select-group-children.component.html
- src/app/child-dev-project/children/select-group-children/select-group-children.component.spec.ts
- src/app/child-dev-project/children/select-group-children/select-group-children.component.ts
Make filtering by class available in roll call feature. This is a first stept towards the larger solution in #369 to make the most important function available to users quickly.
> Filter by class in roll call

- src/app/child-dev-project/children/child-details/child-details.component.html
> WIP: Child Details' Attendance tables overlap on smaller screens

- src/app/core/ui/search/search.component.html
- src/app/core/ui/ui/ui.component.html
simply deleted an fxHide.xs in ui.component
> fixed not showing search button on xs device

- src/app/child-dev-project/children/children.module.ts
- src/app/child-dev-project/children/children.service.ts
- src/app/child-dev-project/dashboard/dashboard/dashboard.component.html
- src/app/child-dev-project/notes/dashboard-widgets/recent-notes-dashboard/recent-notes-dashboard.component.html
- src/app/child-dev-project/notes/dashboard-widgets/recent-notes-dashboard/recent-notes-dashboard.component.scss
- src/app/child-dev-project/notes/dashboard-widgets/recent-notes-dashboard/recent-notes-dashboard.component.spec.ts
- src/app/child-dev-project/notes/dashboard-widgets/recent-notes-dashboard/recent-notes-dashboard.component.ts
- src/app/core/user/user.ts
add a new Dashboard Widget to display count of children with recent notes
> Notes dashboard2

- .gitignore
- proxy.conf.json
- src/app/app.module.ts
- src/app/child-dev-project/children/child-select/child-select.component.ts
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.spec.ts
- src/app/core/database/pouch-database.ts
- src/app/core/latest-changes/update-manager.service.ts
- src/app/core/logging/logging.service.ts
- src/app/core/session/session-service/local-session.ts
see issue: #448 
**Bugfixes:**
> Logging and bugfixes

- src/app/child-dev-project/children/child-details/child-details.component.html
- src/app/child-dev-project/children/child-details/child-details.component.ts
see issue: #476
- error message more specific
- Required fields get marked upon pressing save
> Input error fix

- .github/workflows/deploy-compodoc.yml
- .github/workflows/deploy-pr.yml
- .github/workflows/remove_deployment.yml
- .travis.yml
- CONTRIBUTING.md
- README.md
- package-lock.json
see issue: #411 
In this PR I create a workflow which will automatically deploy the website from each pull request to GitHub Pages so reviews can be done more efficiently without having to checkout each of them locally.
Steps:
> Test deploys

- src/app/child-dev-project/notes/interaction-types.enum.ts
- src/app/child-dev-project/notes/model/note.ts
add a new note category "Ration Distribution" that can be selected by users when creating notes.
(We really need to make this configurable through the user interface to avoid such trivial code changes ...)
> fix(*): add new note category "Ration Distribution"

- src/app/child-dev-project/attendance/model/attendance-month.spec.ts
- src/app/core/entity/schema-datatypes/datatype-month.ts
- src/app/core/entity/schema/entity-schema.service.spec.ts
- src/assets/config.default.json
see issue: #473
Fixed error (in Safari) with missing leading zero in month of date
> Fix safari date issue

- src/app/child-dev-project/children/children-list/children-list.component.ts
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.ts
- src/app/child-dev-project/previous-schools/previous-schools.component.ts
- src/app/child-dev-project/schools/schools-list/schools-list.component.ts
> Grade alphanumeric

- src/app/child-dev-project/attendance/add-month-attendance/add-month-attendance.component.html
- src/app/child-dev-project/attendance/attendance-analysis/attendance-analysis.component.html
- src/app/child-dev-project/attendance/attendance-block/attendance-block.component.html
- src/app/child-dev-project/children/child-block/child-block.component.html
- src/app/child-dev-project/children/children-list/children-list.component.html
- src/app/child-dev-project/children/children-list/children-list.component.scss
- src/app/child-dev-project/notes/dashboard-widgets/no-recent-notes-dashboard/no-recent-notes-dashboard.component.html
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.html
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.scss
- src/app/child-dev-project/schools/school-block/school-block.component.html
- src/app/child-dev-project/schools/school-details/school-details.component.html
- src/app/child-dev-project/schools/schools-list/schools-list.component.html
- src/app/child-dev-project/schools/schools-list/schools-list.component.scss
- src/app/conflict-resolution/conflict-resolution-list/conflict-resolution-list.component.html
- src/app/core/admin/user-list/user-list.component.html
- src/app/core/entity-subrecord/entity-subrecord/entity-subrecord.component.html
- src/app/core/latest-changes/changelog/changelog.component.html
- src/app/core/session/login/login.component.html
- src/app/core/ui/search/search.component.html
- src/app/core/ui/ui/ui.component.html
> Decreased elevation in various ui components

- src/app/child-dev-project/attendance/demo-attendance-generator.service.ts
- src/app/child-dev-project/notes/demo-data/demo-note-generator.service.ts
- src/app/child-dev-project/progress-dashboard-widget/demo-progress-dashboard-widget-generator.service.ts
- src/app/core/database/mock-database.ts
improve some demo data details and mock database implementations
> Demo improvements

- e2e/app.e2e-spec.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
- src/app/core/user/demo-user-generator.service.ts
> Minor fixes

- .github/workflows/master-push.yml
> Semantic fix

- src/app/child-dev-project/aser/aser-component/aser.component.ts
- src/app/child-dev-project/attendance/child-attendance/child-attendance.component.ts
- src/app/child-dev-project/children/child-block/child-block.component.html
- src/app/child-dev-project/educational-material/educational-material-component/educational-material.component.ts
- src/app/child-dev-project/health-checkup/health-checkup-component/health-checkup.component.ts
- src/app/child-dev-project/notes/demo-data/demo-note-generator.service.ts
- src/app/child-dev-project/notes/notes-of-child/notes-of-child.component.ts
- src/app/child-dev-project/previous-schools/previous-schools.component.ts
- src/app/child-dev-project/schools/children-overview/children-overview.component.ts
- src/app/core/entity-components/entity-subrecord/column-description.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord.component.html
- src/app/core/entity-components/entity-subrecord/entity-subrecord.component.scss
- src/app/core/entity-components/entity-subrecord/entity-subrecord.component.spec.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord.component.ts
> Please merge without sqashing.
> Entity Subrecord adaptions

- src/app/app.module.ts
- src/app/child-dev-project/attendance/attendance-analysis/attendance-analysis.component.ts
- src/app/child-dev-project/notes/model/note.ts
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.spec.ts
- src/app/core/config/config-fix.json
- src/app/core/entity-components/entity-details/entity-details.module.ts
- src/app/core/entity-components/entity-details/form/form.component.html
- src/app/core/entity-components/entity-details/form/form.component.spec.ts
- src/app/core/entity-components/entity-list/EntityListConfig.ts
- src/app/core/entity-components/entity-list/display-configurable-enum/display-configurable-enum.component.spec.ts
- src/app/core/entity-components/entity-list/display-configurable-enum/display-configurable-enum.component.ts
- src/app/core/entity-components/entity-list/entity-list.component.html
- src/app/core/entity-components/entity-list/entity-list.component.scss
- src/app/core/entity-components/entity-list/entity-list.component.spec.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
- src/app/core/entity-components/entity-list/entity-list.module.ts
- src/app/core/entity-components/entity-list/list-filter/list-filter.component.html
- src/app/core/entity-components/entity-list/list-filter/list-filter.component.spec.ts
- src/app/core/entity-components/entity-list/list-filter/list-filter.component.ts
- src/app/core/filter/filter-selection/filter-selection.spec.ts
- src/app/core/filter/filter-selection/filter-selection.ts
- src/app/core/view/dynamic-components-map.ts
- src/app/core/view/view.module.ts
required for adaptions for new customers
> please merge without sqashing
> Components and Filter for ConfigurableEnum values

- package-lock.json
- package.json
- src/app/core/admin/admin/admin.component.ts
Removing the FileSaver dependency, because it is not really needed and difficult to test.
- Removed FileSaver dependency
- Replaced code for downloading files
> Remove FileSaver dependency

- src/app/child-dev-project/progress-dashboard-widget/progress-dashboard/progress-dashboard.component.ts
- src/app/core/alerts/alert.service.spec.ts
- src/app/core/alerts/alert.service.ts
- src/app/core/alerts/alert.ts
- src/app/core/analytics/analytics.service.ts
- src/app/core/config/config-fix.json
- src/app/core/database/pouch-database.spec.ts
- src/app/core/database/pouch-database.ts
- src/app/core/demo-data/demo-data.service.ts
- src/app/core/latest-changes/latest-changes.service.spec.ts
- src/app/core/session/session-service/synced-session.service.spec.ts
- src/app/core/session/session-service/synced-session.service.ts
- src/app/core/view/dynamic-routing/router.service.ts
- src/app/core/view/dynamic-routing/view-config.interface.ts
see issue: #468, #605
- _none_
-  see commit messages
> please merge without sqashing!
> Improve analytics and logging

- src/app/core/user/user-account/user-account.component.ts
- src/app/core/webdav/cloud-file-service.service.ts
- src/app/core/webdav/webdav.module.ts
default config sets webdav with remote_url = null and wrongly activated webdav connection here
> fix: only init cloud-file-service if an actual remote_url is defined

- src/app/app.module.ts
- src/app/child-dev-project/attendance/attendance-calendar/attendance-calendar.component.scss
- src/app/child-dev-project/attendance/attendance-calendar/attendance-calendar.component.ts
- src/app/child-dev-project/attendance/demo-activity-events-generator.service.ts
- src/app/child-dev-project/attendance/demo-activity-generator.service.ts
- src/app/core/config/config-fix.ts
- src/app/core/config/config.service.ts
- src/app/core/config/default-config/default-attendance-status-types.ts
- src/app/core/config/default-config/default-interaction-types.ts
generate demo events including individual attendance for every RecurringActivity
> Demo event attendance [Event Attendance Part +2]

- src/app/child-dev-project/attendance/attendance-block/attendance-block.component.html
- src/app/child-dev-project/attendance/attendance-block/attendance-block.component.spec.ts
- src/app/child-dev-project/attendance/attendance-block/attendance-block.component.ts
- src/app/child-dev-project/attendance/attendance-block/attendance-block.stories.ts
- src/app/child-dev-project/attendance/attendance-status-select/attendance-status-select.stories.ts
- src/app/child-dev-project/attendance/attendance.service.ts
- src/app/child-dev-project/attendance/model/activity-attendance.spec.ts
- src/app/child-dev-project/attendance/model/activity-attendance.ts
- src/app/child-dev-project/children/children-list/recent-attendance-blocks/recent-attendance-blocks.component.spec.ts
- src/app/child-dev-project/children/children-list/recent-attendance-blocks/recent-attendance-blocks.component.ts
- src/app/core/config/config-fix.ts
update AttendanceBlock components to display new attendance data model
> Attendance blocks for lists  [Event Attendance Part +3]

- .github/workflows/master-push.yml
- .releaserc
see issue: #612 
- Creating tar archive with `dist` folder
- Publishing GitHub release with tar archive
> Create GitHub Releases

- src/app/child-dev-project/children/children-count-dashboard/children-count-dashboard.component.html
- src/app/child-dev-project/children/children-count-dashboard/children-count-dashboard.component.spec.ts
- src/app/child-dev-project/children/children-count-dashboard/children-count-dashboard.component.ts
- src/app/child-dev-project/children/model/child.ts
see commits
> please merge without squashing
> Some minor improvements for configurability

- .github/workflows/master-push.yml
A small CleanUp of the pipeline due to the removal of the GitHub release asset.
- Remove `exec` plugin
- Remove `dist` artifact
> Pipeline CleanUp

- src/app/core/config/config-fix.json
- src/app/core/entity-components/entity-list/EntityListConfig.ts
- src/app/core/entity-components/entity-list/entity-list.component.spec.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
see issue: #559
- Column groups are optional in config and default to all columns
- Filters are optional in config and default to no filters
> ColumnGroups and Filters are optional in config

- src/app/child-dev-project/children/children.module.ts
- src/app/child-dev-project/previous-teams/previous-teams.component.html
- src/app/child-dev-project/previous-teams/previous-teams.component.spec.ts
- src/app/child-dev-project/previous-teams/previous-teams.component.ts
- src/app/core/config/config-fix.ts
- src/app/core/entity-components/entity-details/entity-details.component.ts
- src/app/core/view/dynamic-components-map.ts
add alternative component styled for teams instead of schools
> Previous teams

- src/app/child-dev-project/children/children-count-dashboard/children-count-dashboard.component.html
- src/app/core/entity-components/entity-list/entity-list.component.ts
- src/app/core/entity/entity-config.service.ts
> fix(core): prevent errors if entities are not in config

- src/app/child-dev-project/children/children-list/bmi-block/bmi-block.component.scss
- src/app/child-dev-project/children/children-list/bmi-block/bmi-block.component.spec.ts
- src/app/child-dev-project/children/children-list/bmi-block/bmi-block.component.ts
- src/app/child-dev-project/children/children.module.ts
- src/app/core/config/config-fix.json
- src/app/core/entity-components/entity-subrecord/entity-subrecord.component.ts
- src/app/core/session/session-service/online-session.service.ts
- src/app/core/view/dynamic-components-map.ts
> BMI List Feature

- src/app/child-dev-project/attendance/attendance.service.spec.ts
- src/app/child-dev-project/attendance/attendance.service.ts
- src/app/child-dev-project/attendance/model/recurring-activity.ts
- src/app/child-dev-project/children/children-list/recent-attendance-blocks/recent-attendance-blocks.component.spec.ts
- src/app/child-dev-project/children/children-list/recent-attendance-blocks/recent-attendance-blocks.component.ts
- src/app/core/entity/database-indexing/database-indexing.service.ts
- src/app/utils/performance-tests.spec.ts
implement database indices for queries
> Event indices [Event Attendance +1]

- src/app/child-dev-project/attendance/attendance-month-conflict-resolution.spec.ts
- src/app/core/entity/schema-datatypes/datatype-number.ts
- src/app/core/entity/schema-datatypes/datatype-string.ts
(deactivated one test that will become obsolete with new event attendance anyway)
> fix(core): correctly handle empty values that are not undefined in schema datatypes

- src/app/child-dev-project/attendance/attendance-month-conflict-resolution.spec.ts
- src/app/child-dev-project/children/child-photo-service/datatype-load-child-photo.spec.ts
- src/app/child-dev-project/children/model/child.spec.ts
- src/app/child-dev-project/children/model/child.ts
- src/app/core/entity/schema-datatypes/datatype-date-only.ts
- src/app/core/entity/schema-datatypes/datatype-date.ts
- src/app/core/entity/schema-datatypes/datatype-month.ts
- src/app/core/entity/schema-datatypes/datatype-number.ts
- src/app/core/entity/schema-datatypes/datatype-string.ts
- src/app/core/entity/schema/entity-schema-field.ts
- src/app/core/entity/schema/entity-schema.service.ts
handle "undefined" values in schema transformations more consistently
> Fix datatype undefined

- src/app/child-dev-project/attendance/child-attendance/child-attendance.component.ts
- src/app/child-dev-project/notes/notes-of-child/notes-of-child.component.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord.component.ts
> fix(*): fix error when trying to open details of an attendance record of child details

- src/app/child-dev-project/children/children-list/children-list.component.spec.ts
- src/app/child-dev-project/children/children-list/children-list.component.ts
- src/app/child-dev-project/children/children.service.spec.ts
- src/app/core/config/config-fix.json
- src/app/core/database/mock-database.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
see issue: #637
Currently the filter only works with the `schoolId` field. Due to the current status, I dont think a more general/flexible approach is required.
- Added a filter for schools in the children list section
- Added a prebuilt filter for the `ChildrenListComponent`
> School filter

- src/app/core/permissions/permissions.module.ts
> fix(*): removed unnecessary export

- src/app/child-dev-project/schools/children-overview/children-overview.component.spec.ts
- src/app/child-dev-project/schools/children-overview/children-overview.component.ts
- src/app/core/entity-components/entity-list/entity-list.component.spec.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
> Non-standard objects can be sorted

- src/app/child-dev-project/attendance/attendance-block/attendance-block.component.ts
- src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-day-block/attendance-day-block.component.html
- src/app/child-dev-project/children/child-block/child-block.component.ts
- src/app/child-dev-project/schools/school-block/school-block.component.ts
> Tooltip delay

- src/app/app.module.ts
- src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-week-dashboard.component.scss
- src/app/child-dev-project/children/children-bmi-dashboard/children-bmi-dashboard.component.scss
- src/app/child-dev-project/children/children-bmi-dashboard/children-bmi-dashboard.component.ts
- src/app/child-dev-project/children/children-count-dashboard/children-count-dashboard.component.scss
- src/app/child-dev-project/notes/dashboard-widgets/no-recent-notes-dashboard/no-recent-notes-dashboard.component.scss
- src/app/child-dev-project/progress-dashboard-widget/progress-dashboard/progress-dashboard.component.scss
- src/app/core/config/config-fix.ts
- src/app/core/dashboard-shortcut-widget/dashboard-shortcut-widget.module.ts
- src/app/core/dashboard-shortcut-widget/dashboard-shortcut-widget/dashboard-shortcut-widget.component.html
- src/app/core/dashboard-shortcut-widget/dashboard-shortcut-widget/dashboard-shortcut-widget.component.scss
- src/app/core/dashboard-shortcut-widget/dashboard-shortcut-widget/dashboard-shortcut-widget.component.spec.ts
- src/app/core/dashboard-shortcut-widget/dashboard-shortcut-widget/dashboard-shortcut-widget.component.ts
- src/app/core/dashboard-shortcut-widget/dashboard-shortcut-widget/dashboard-shortcut-widget.stories.ts
- src/app/core/dashboard/dashboard-widget-base.scss
- src/app/core/navigation/menu-item.ts
- src/app/core/navigation/navigation/navigation.component.html
- src/app/core/navigation/navigation/navigation.component.spec.ts
- src/app/core/navigation/navigation/navigation.component.ts
- src/app/core/view/dynamic-components-map.ts
- src/styles.scss
~see issue~
_Merge without squashing to keep the refactoring commits in the git history_
> Dashboard shortcut widget

- src/app/core/entity-components/entity-list/entity-list.component.spec.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
better usability, especially NotesManager, with reasonable sorting by default.
> feat: sort lists automatically by first column

- build/Dockerfile
- package.json
Updated base image of the Dockerfile.
--
- using Node version 15.11
- Using Nginx version 1.19.9
- Only running lint in `src/app`
> Updated Docker Image

- src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.ts
- src/app/child-dev-project/children/child-block-list/child-block-list.component.html
- src/app/child-dev-project/children/child-block-list/child-block-list.component.spec.ts
- src/app/child-dev-project/children/child-block-list/child-block-list.component.ts
- src/app/child-dev-project/children/child-block/child-block.component.html
- src/app/child-dev-project/schools/school-block/school-block.component.ts
> Note and Attendance fixes

- src/app/child-dev-project/notes/notes-manager/notes-manager.component.html
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.scss
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.spec.ts
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.ts
- src/app/child-dev-project/notes/notes.module.ts
- src/app/core/config/config-fix.ts
show events of recurring activities (`EventNote` entities) in the notes list and make that option configurable
> feat(attendance): show events of recurring activities in the notes list

- src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.ts
- src/app/child-dev-project/attendance/attendance.service.spec.ts
- src/app/child-dev-project/attendance/attendance.service.ts
- src/app/child-dev-project/children/children.service.spec.ts
- src/app/child-dev-project/children/children.service.ts
- src/app/child-dev-project/notes/model/note.ts
- src/app/core/database/mock-database.ts
- src/app/utils/expect-entity-data.spec.ts
also load Note instances that are of "isMeeting" categories as available events for roll calls.
> fix(attendance): display manually created events in "Record Attendance" setup

- src/app/child-dev-project/attendance/attendance-migration/attendance-migration.service.spec.ts
- src/app/child-dev-project/attendance/attendance-migration/attendance-migration.service.ts
- src/app/child-dev-project/attendance/attendance.service.ts
- src/app/child-dev-project/children/children-list/recent-attendance-blocks/recent-attendance-blocks.component.ts
- src/app/core/admin/admin/admin.component.html
- src/app/core/admin/admin/admin.component.spec.ts
- src/app/core/admin/admin/admin.component.ts
- src/app/core/entity/schema-datatypes/datatype-date.ts
> small attendance migration patch-ups

- src/app/child-dev-project/attendance/attendance.service.spec.ts
- src/app/child-dev-project/attendance/attendance.service.ts
- src/app/child-dev-project/children/children-list/children-list.component.spec.ts
- src/app/child-dev-project/children/children-list/children-list.component.ts
- src/app/child-dev-project/children/model/childSchoolRelation.ts
- src/app/child-dev-project/schools/school-block/school-block.component.html
- src/app/core/config/config-fix.ts
- src/app/core/entity-components/entity-list/entity-list.component.spec.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
> Ux improvements

- src/app/child-dev-project/attendance/attendance.service.spec.ts
- src/app/child-dev-project/attendance/attendance.service.ts
A little refactor that might fix the sometimes failing unit tests
> fix: failing unit test

- src/app/conflict-resolution/auto-resolution/auto-resolution.service.ts
- src/app/core/database/pouch-database.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
- src/app/core/logging/logging.service.ts
- src/app/core/session/session-service/synced-session.service.spec.ts
- src/app/core/session/session-service/synced-session.service.ts
- src/app/core/sync-status/sync-status/sync-status.component.ts
> Logging cleanup

- src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.scss
- src/app/core/ui/ui/ui.component.html
- src/app/core/ui/ui/ui.component.scss
> Mobile layout fixes

- src/app/core/ui/ui/ui.component.spec.ts
(previous commit was accidentally pushed to master already)
> test: fix test for logo fix

- src/app/core/sync-status/background-processing-indicator/background-processing-indicator.component.html
- src/app/core/sync-status/background-processing-indicator/background-processing-indicator.component.spec.ts
- src/app/core/sync-status/background-processing-indicator/background-processing-indicator.component.ts
- src/app/core/sync-status/sync-status/sync-status.component.html
See issue #820 
Modernizes the architecture for the sync status by taking advantage of `rxJs` and asynchronous processing of the data.
This fixes #820 by creating a new `BackgroundProcessState` instead of altering the given state which in turn alters internal data from the `DatabaseIndexingService` causing certain indices to look like they are not registered
> refactor sync status

- src/app/core/dashboard-shortcut-widget/dashboard-shortcut-widget/dashboard-shortcut-widget.stories.ts
- src/app/core/navigation/menu-item.ts
- src/app/core/navigation/navigation/navigation.component.html
- src/app/core/navigation/navigation/navigation.component.scss
- src/app/core/navigation/navigation/navigation.component.spec.ts
- src/app/core/navigation/navigation/navigation.component.ts
> Highlight menu entry

- src/app/child-dev-project/children/children-bmi-dashboard/children-bmi-dashboard.component.html
- src/app/core/ui/primary-action/primary-action.component.html
naming of events tracked to Matomo was not consistent sometimes
> refactor: correct angulartics / matomo tracking event names

- src/app/child-dev-project/aser/aser-component/aser.component.ts
- src/app/child-dev-project/educational-material/educational-material-component/educational-material.component.ts
- src/app/child-dev-project/health-checkup/health-checkup-component/health-checkup.component.ts
- src/app/child-dev-project/notes/notes-of-child/notes-of-child.component.ts
- src/app/child-dev-project/schools/children-overview/children-overview.component.ts
- src/app/core/admin/admin/admin.component.html
- src/app/core/admin/admin/admin.component.spec.ts
- src/app/core/admin/admin/admin.component.ts
- src/app/core/config/config-migration.service.spec.ts
- src/app/core/config/config-migration.service.ts
- src/app/core/config/config.service.ts
- src/app/core/entity-components/entity-details/entity-details.component.ts
- src/app/core/entity-components/entity-utils/entity-select/entity-select.component.html
An automated migration for the old config format.
The new config is very compatible with the old format, only the fields and some input types have to be renamed
> Config migration

- src/app/core/entity-components/entity-utils/entity-select/entity-select.component.spec.ts
- src/app/core/ui/search/search.component.html
- src/app/core/ui/search/search.component.spec.ts
- src/app/core/ui/search/search.component.ts
- src/app/core/ui/ui.module.ts
> Modernize Search Bar

- angular.json
- package-lock.json
- package.json
- src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.html
- src/app/child-dev-project/attendance/attendance-calendar/attendance-calendar.component.html
- src/app/child-dev-project/attendance/attendance-manager/attendance-manager.component.html
- src/app/child-dev-project/notes/note-details/note-details.component.html
- src/app/child-dev-project/progress-dashboard-widget/demo-progress-dashboard-widget-generator.service.ts
- src/app/conflict-resolution/conflict-resolution-list/conflict-resolution-list.component.html
- src/app/core/config/Beispielconfig auf Deutsch.json
- src/app/core/entity/entity.ts
- src/locale/messages.de.xlf
- src/locale/messages.xlf
Improvement of the German language version
(in the code + addition of the file "Beispielconfig auf Deutsch.json")
> I18n update for german

- src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.ts
> - fix bug popup scroll

- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-number/edit-number.component.html
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-number/edit-number.component.spec.ts
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-number/edit-number.component.ts
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-number/edit-number.stories.ts
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-percentage/edit-percentage.component.html
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-percentage/edit-percentage.component.spec.ts
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-percentage/edit-percentage.component.ts
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-percentage/edit-percentage.stories.ts
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-text/edit-text.component.html
- src/app/utils/custom-number-validators.ts
- src/locale/messages.de.xlf
- src/locale/messages.xlf
> fix(*): allow decimals in number and percentage fields

- src/app/child-dev-project/attendance/attendance-details/attendance-details.component.html
- src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.ts
- src/app/core/form-dialog/form-dialog-wrapper/form-dialog-wrapper.component.html
- src/app/core/form-dialog/form-dialog-wrapper/form-dialog-wrapper.component.ts
- src/app/core/form-dialog/form-dialog.service.ts
> fix(*): remove wrongly visible edit buttons on attendance details popup

- src/app/core/entity-components/entity-utils/view-components/display-entity-array/display-entity-array.component.html
> - fix separation of column

- src/app/core/latest-changes/latest-changes.module.ts
- src/app/core/latest-changes/latest-changes.service.spec.ts
- src/app/core/latest-changes/latest-changes.service.ts
excludes prerelease versions
removes lines marked as hidden by starting with .
fixes #925
> fix(changelog): remove irrelevant versions and details

- src/app/core/latest-changes/changelog/changelog.component.ts
to prevent .length of undefined error in sentry
> fix(core): .add safeguard if changelogs not loaded

- src/app/app.component.ts
- src/app/child-dev-project/children/children-bmi-dashboard/children-bmi-dashboard.component.ts
- src/app/child-dev-project/children/children-count-dashboard/children-count-dashboard.component.ts
- src/app/child-dev-project/children/children-list/children-list.component.ts
- src/app/child-dev-project/children/children-list/recent-attendance-blocks/recent-attendance-blocks.component.ts
- src/app/core/admin/admin/admin.component.ts
- src/app/core/entity-components/entity-details/entity-details.component.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.ts
- src/app/core/form-dialog/form-dialog-wrapper/form-dialog-wrapper.component.ts
- src/app/core/latest-changes/changelog/changelog.component.ts
- src/app/core/navigation/navigation/navigation.component.ts
sometimes tests are throwing `Object unsubscribe error` this might fix the problem
> fix: added unsubscribe calls to observables

- src/app/utils/performance-tests.spec.ts
> Utility function for performance testing

- src/app/core/config/config-fix.ts
export format config as a sample
> chore(demo): use the new export config for a custom event export

- src/app/core/config/config-migration.service.spec.ts
- src/app/core/config/config.service.ts
currently the config migration doesnt work because of a document update conflict.
> fix: migrate config with force update

- src/app/core/export/export-service/export.service.spec.ts
- src/app/core/export/export-service/export.service.ts
> Date export fix

- src/app/child-dev-project/children/model/genders.ts
- src/locale/messages.de.xlf
- src/locale/messages.xlf
> Add "divers" or "non-binary" as possible gender option

- src/app/child-dev-project/children/children-list/children-list.component.spec.ts
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.scss
- src/app/core/admin/admin.module.ts
- src/app/core/admin/export-data/export-data.component.html
- src/app/core/admin/export-data/export-data.component.scss
- src/app/core/admin/export-data/export-data.directive.spec.ts
- src/app/core/admin/export-data/export-data.directive.ts
- src/app/core/config/config-fix.ts
- src/app/core/entity-components/entity-list/EntityListConfig.ts
- src/app/core/entity-components/entity-list/entity-list.component.html
- src/app/core/entity-components/entity-list/entity-list.component.scss
- src/app/core/entity-components/entity-list/entity-list.component.spec.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
- src/app/core/entity-components/entity-list/entity-list.module.ts
- src/app/core/entity-components/entity-list/list-filter/list-filter.component.html
- src/app/core/entity-components/entity-list/list-filter/list-filter.component.scss
- src/app/core/ui/ui/ui.component.html
- src/app/features/reporting/reporting/reporting.component.html
- src/styles.scss
> [WIP] UX list improvement

- .github/workflows/master-push.yml
- .github/workflows/pull-request-update.yml
- README.md
> added workflow for dependency checking with snyk

- src/app/child-dev-project/notes/note-details/note-details.component.html
> Set initial focus to the subject of a note

- .github/workflows/master-push.yml
- .github/workflows/pull-request-update.yml
- .github/workflows/tagged-commit.yml
> ci: changed all checkout usages to v2

- src/app/core/export/export-service/export.service.ts
- src/app/features/reporting/query.service.spec.ts
- src/app/features/reporting/query.service.ts
Currently some exports/reports dont work if children have been deleted
> Fix deleted participants export

- src/app/child-dev-project/progress-dashboard-widget/progress-dashboard/progress-dashboard.component.spec.ts
- src/app/child-dev-project/progress-dashboard-widget/progress-dashboard/progress-dashboard.component.ts
see issue: #1140 
The progress dashboard component saves data after changes
> Progress is saved correctly after closing the dialog

- src/app/child-dev-project/children/previous-schools/previous-schools.component.ts
- src/app/core/config/config-fix.ts
- src/app/core/entity-components/entity-list/filter-predicate.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.spec.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord/sorting-accessor.spec.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord/sorting-accessor.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord/table-sort.spec.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord/table-sort.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord/value-accessor.spec.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord/value-accessor.ts
- src/app/core/export/export-service/export.service.spec.ts
- src/app/core/export/export-service/export.service.ts
> fix: sort is not case sensitive

- src/app/core/entity-components/entity-details/entity-details.component.html
> disabling other sections when creating a new entity

- src/app/core/entity-components/entity-form/entity-form.service.spec.ts
Fixed a wrong written test
--
--
> fixed wrong test

- src/app/core/entity-components/entity-list/entity-list.component.html
> fix: List filter box is always shown

- src/app/child-dev-project/attendance/activity-attendance-section/activity-attendance-section.component.html
- src/app/child-dev-project/attendance/activity-attendance-section/activity-attendance-section.component.ts
- src/app/child-dev-project/attendance/model/activity-attendance.ts
- src/app/core/ui/ui/ui.component.scss
- src/app/pwa-install/pwa-install.component.html
- src/app/pwa-install/pwa-install.component.spec.ts
- src/app/pwa-install/pwa-install.module.ts
see commits [please do not sqash, rebase instead]
> small fixes

- src/app/app.module.ts
- src/app/core/session/session-service/synced-session.service.ts
- src/app/core/support/support.module.ts
- src/app/core/support/support/support.component.spec.ts
- src/app/core/support/support/support.component.ts
The sync state was set in a wrongly used module and did therefore not work properly. Moved it to the `SyncedSessionService` now.
--
> fix: last sync state is correctly set

- src/app/child-dev-project/children/child-block/child-block.component.html
- src/app/child-dev-project/children/child-block/child-block.component.scss
- src/app/child-dev-project/schools/school-block/school-block.component.html
- src/app/core/entity-components/entity-utils/entity-select/entity-select.component.html
- src/app/core/entity-components/entity-utils/entity-select/entity-select.component.scss
- src/app/core/entity-components/entity-utils/view-components/display-entity/display-entity.component.html
- src/app/core/entity-components/entity-utils/view-components/display-entity/display-entity.component.scss
- src/styles.scss
allow navigation to entities from disabled entity-select and correctly visualize when navigation is disabled
> fix: allow navigation to entities from disabled entity-select

- src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.html
- src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.scss
- src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.spec.ts
- src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.ts
- src/app/core/form-dialog/form-dialog-wrapper/form-dialog-wrapper.component.html
- src/app/core/form-dialog/form-dialog-wrapper/form-dialog-wrapper.component.spec.ts
- src/app/core/form-dialog/form-dialog-wrapper/form-dialog-wrapper.component.ts
> feat(attendance): allow reviewing/editing of an event after roll call

- src/app/core/support/support/support.component.html
- src/app/core/support/support/support.component.ts
Sometimes the app is suddenly not working offline anymore. This might be due to limited storage available
--
> added storage information to support panel

- src/locale/messages.de.xlf
- src/locale/messages.fr.xlf
- src/locale/messages.xlf
> added missing translations

- src/app/core/config/config-fix.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
... especially when some column is dynamically resizing
> fix(*): prevent unwanted switches to list default columns

- .github/workflows/pre-release-cleanup.yml
- package-lock.json
- package.json
- src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.spec.ts
- src/app/child-dev-project/attendance/attendance.service.spec.ts
- src/app/child-dev-project/attendance/attendance.service.ts
- src/app/child-dev-project/children/children.service.spec.ts
- src/app/child-dev-project/children/children.service.ts
- src/app/child-dev-project/children/model/childSchoolRelation.ts
- src/app/child-dev-project/children/previous-schools/previous-schools.component.spec.ts
- src/app/child-dev-project/children/previous-schools/previous-schools.component.ts
- src/app/child-dev-project/schools/children-overview/children-overview.component.spec.ts
- src/app/child-dev-project/schools/children-overview/children-overview.component.ts
- src/app/core/config/config-fix.ts
- src/app/core/entity-components/entity-details/entity-details.component.spec.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
- src/app/features/historical-data/historical-data.service.ts
> Release 3.6.1

- src/app/child-dev-project/children/child-block/child-block.component.html
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-photo/edit-photo.component.html
- src/locale/messages.de.xlf
- src/locale/messages.fr.xlf
- src/locale/messages.xlf
> fix(*): Removed alt text from images

- src/app/child-dev-project/notes/note-details/child-meeting-attendance/child-meeting-note-attendance.component.html
> fix(*): Edit button is enabled when adding remarks

- src/app/core/session/session-service/local-session.spec.ts
- src/app/core/session/session-service/local-session.ts
> Release 3.7.1

- src/app/child-dev-project/children/dashboard-widgets/birthday-dashboard/birthday-dashboard.component.ts
> Release 3.8.1

- package-lock.json
- package.json
- src/app/app.routing.ts
- src/app/child-dev-project/children/children-list/children-list.component.spec.ts
- src/app/child-dev-project/children/children-list/children-list.component.ts
- src/app/child-dev-project/children/dashboard-widgets/birthday-dashboard/birthday-dashboard.component.ts
- src/app/core/config/config-fix.ts
- src/app/core/entity-components/entity-list/filter-generator.service.ts
- src/app/core/entity/schema-datatypes/datatype-date-only.spec.ts
- src/app/core/entity/schema-datatypes/datatype-date-only.ts
- src/app/core/entity/schema-datatypes/datatype-month.ts
- src/app/core/support/support.module.ts
- src/app/core/support/support/support.component.ts
- src/app/core/user/user-account/user-account.component.ts
- src/app/core/user/user.module.ts
- src/app/core/view/dynamic-routing/not-found/not-found.component.spec.ts
- src/app/core/view/dynamic-routing/not-found/not-found.component.ts
- src/app/core/view/dynamic-routing/router.service.spec.ts
- src/app/core/view/dynamic-routing/router.service.ts
- src/app/features/data-import/data-import.service.ts
- src/app/features/data-import/data-import/data-import.component.html
- src/app/features/data-import/data-import/data-import.component.spec.ts
- src/app/features/data-import/data-import/data-import.component.ts
- src/app/features/data-import/import-meta-data.type.ts
> Release 3.8.2

- src/app/app.routing.ts
- src/app/child-dev-project/attendance/attendance.service.spec.ts
- src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-week-dashboard.component.html
- src/app/child-dev-project/children/child-block/child-block.component.html
- src/app/child-dev-project/children/child-block/child-block.component.ts
- src/app/child-dev-project/children/dashboard-widgets/birthday-dashboard/birthday-dashboard.component.html
- src/app/child-dev-project/children/dashboard-widgets/children-bmi-dashboard/children-bmi-dashboard.component.html
- src/app/child-dev-project/notes/dashboard-widgets/notes-dashboard/notes-dashboard.component.html
- src/app/child-dev-project/notes/note-details/child-meeting-attendance/child-meeting-note-attendance.component.html
- src/app/child-dev-project/notes/note-details/note-details.component.html
- src/app/child-dev-project/notes/note-details/note-details.component.spec.ts
- src/app/child-dev-project/schools/school-block/school-block.component.ts
- src/app/core/config/config-fix.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
- src/app/core/entity-components/entity-utils/view-components/display-entity/display-entity.component.html
- src/app/core/entity-components/entity-utils/view-components/display-entity/display-entity.component.spec.ts
- src/app/core/entity-components/entity-utils/view-components/display-entity/display-entity.component.ts
- src/app/core/entity/schema-datatypes/datatype-date-only.spec.ts
- src/app/core/entity/schema-datatypes/datatype-date-only.ts
- src/app/core/entity/schema-datatypes/datatype-map.spec.ts
- src/app/core/entity/schema/entity-schema.service.spec.ts
- src/app/core/ui/ui/ui.component.html
- src/app/utils/test-utils/generic-matchers.spec.ts
> Release 3.8.3

- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-single-entity/edit-single-entity.component.html
A comment in the `EditSingle EntityComponent` didn't actually explain the double `inputs` and was confusing
> Clarify comment

- src/app/core/permissions/permission-directive/disable-entity-operation.directive.ts
- src/app/core/view/dynamic-components/dynamic-component.directive.ts
Replace all uses of the `ComponentFactoryResolver` since it is deprecated and there are simpler alternatives
> Remove ComponentFactoryResolver

- src/app/child-dev-project/notes/model/note.ts
> fixed broken ordering for note category

- src/app/child-dev-project/notes/model/note.ts
> Release 3.9.2

- src/app/app.module.ts
- src/app/core/app-config/app-settings.ts
- src/main.ts
> fix: bootstrap logging

- src/app/app.module.ts
- src/app/core/app-config/app-settings.ts
- src/main.ts
> Bootstrap logging

- src/app/child-dev-project/children/dashboard-widgets/birthday-dashboard/birthday-dashboard.component.html
- src/app/child-dev-project/children/dashboard-widgets/birthday-dashboard/birthday-dashboard.component.ts
- src/assets/locale/messages.de.xlf
- src/assets/locale/messages.fr.xlf
- src/assets/locale/messages.xlf
The birthday dashboard widget does not have a fallback text if not birthdays are in the next 31 days (when the table is empty). This has been fixed.
Also the translation for the fallback text of the BMI widget has been added.
> Birthday dashboard text

- src/app/core/configurable-enum/display-configurable-enum/display-configurable-enum.component.ts
> fix: error when value is not defined

- src/app/core/entity/entity-mapper.service.spec.ts
- src/app/core/entity/entity-mapper.service.ts
This includes the entity ID in the error message. This allows to easier find out which entity is affected by the issue.
> fix: improved error messages for failed database to entity transformation

- src/app/child-dev-project/notes/note-details/note-details.component.html
- src/assets/locale/messages.de.xlf
- src/assets/locale/messages.fr.xlf
- src/assets/locale/messages.it.xlf
- src/assets/locale/messages.xlf
Some of the translations got lost and some strings were missing the i18n tag
> fix: improved translations

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/child-dev-project/attendance/attendance-calendar/attendance-calendar.component.ts
- src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-week-dashboard.component.spec.ts
- src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-week-dashboard.component.ts
- src/app/child-dev-project/notes/dashboard-widgets/important-notes/important-notes.component.html
- src/app/child-dev-project/notes/dashboard-widgets/important-notes/important-notes.component.scss
- src/app/child-dev-project/notes/note-details/note-details.component.html
- src/app/core/entity/entity-mapper.service.spec.ts
- src/app/core/entity/entity-mapper.service.ts
- src/app/core/language/date-adapter-with-formatting.spec.ts
- src/app/core/language/date-adapter-with-formatting.ts
- src/app/core/session/login/login.component.html
- src/app/core/session/login/login.component.scss
- src/app/core/session/login/login.component.spec.ts
- src/app/core/session/login/login.component.ts
- src/app/core/session/session.module.ts
- src/app/features/progress-dashboard-widget/edit-progress-dashboard/edit-progress-dashboard.component.html
- src/app/features/progress-dashboard-widget/edit-progress-dashboard/edit-progress-dashboard.component.scss
- src/app/features/progress-dashboard-widget/edit-progress-dashboard/edit-progress-dashboard.component.spec.ts
- src/app/features/progress-dashboard-widget/edit-progress-dashboard/edit-progress-dashboard.component.ts
- src/app/features/progress-dashboard-widget/progress-dashboard/progress-dashboard.component.ts
- src/assets/locale/messages.de.xlf
- src/assets/locale/messages.fr.xlf
- src/assets/locale/messages.it.xlf
- src/assets/locale/messages.xlf
> Release 3.11.1

- src/app/child-dev-project/notes/dashboard-widgets/important-notes/important-notes.component.ts
- src/assets/locale/messages.de.xlf
> Small improvements

- e2e/support/commands.ts
this should fix the sometimtes failing cypress tests
> test: increased timeout for e2e tests

- .github/workflows/master-push.yml
- .github/workflows/pull-request-closed.yml
- .github/workflows/pull-request-opened.yml
- .github/workflows/pull-request-update.yml
- .github/workflows/semantic-release.yml
- .github/workflows/tagged-commit.yml
The actions currently show warnings:
--
> build: updated actions versions

- src/app/core/session/auth/keycloak/account-page/account-page.component.html
- src/app/core/session/auth/keycloak/account-page/account-page.component.spec.ts
- src/app/core/session/auth/keycloak/account-page/account-page.component.ts
- src/app/core/session/auth/keycloak/keycloak-auth.service.spec.ts
- src/app/core/session/auth/keycloak/keycloak-auth.service.ts
- src/assets/locale/messages.de.xlf
- src/assets/locale/messages.fr.xlf
- src/assets/locale/messages.it.xlf
- src/assets/locale/messages.xlf
> Release 3.13.1

- src/app/features/data-import/data-import.module.ts
- src/app/features/data-import/data-import.service.spec.ts
- src/app/features/data-import/data-import.service.ts
- src/app/features/data-import/data-import/data-import.component.html
- src/app/features/data-import/data-import/data-import.component.spec.ts
- src/app/features/data-import/data-import/data-import.component.ts
- src/app/features/data-import/input-file/input-file.component.html
- src/app/features/data-import/input-file/input-file.component.spec.ts
- src/app/features/data-import/input-file/input-file.component.ts
extract the file loading logic into separate component to simplify the very complex import component a little bit.
> Import UX Refactoring

- src/app/core/config/config-fix.ts
- src/app/core/entity-components/entity-form/entity-form/entity-form.component.html
- src/app/core/entity-components/entity-form/entity-form/entity-form.component.scss
- src/app/core/entity-components/entity-form/entity-form/entity-form.stories.ts
see Child Details --> tooltip for "mothertongue"
> fix(ui): properly position help icon for tooltips next to form fields

- doc/compodoc_sources/concepts/permissions.md
- src/app/core/config/config-fix.ts
- src/app/core/entity-components/entity-form/entity-form/entity-form.component.html
- src/app/core/entity-components/entity-form/entity-form/entity-form.component.scss
- src/app/core/entity-components/entity-form/entity-form/entity-form.stories.ts
- src/app/core/user/user.spec.ts
- src/app/core/user/user.ts
> Release 3.13.3

- src/app/core/user/user-security/user-security.component.ts
> fix: 'user_app' role is automatically assigned for new users

- .github/workflows/pull-request-opened.yml
> ci: PR opened action has permission to post comment

- package-lock.json
- package.json
- src/app/core/user/user-security/user-security.component.html
- src/app/core/user/user.module.ts
Remove the last FxLayout dependency and remove it from the package.json
> Remove flex layout

- src/app/utils/media/screen-size-observer.service.ts
Now it no longer behaves weird.
> Fix: ScreenSizeObserver sometimes behaves weird when the screen width changes

- src/app/child-dev-project/notes/notes-manager/notes-manager.component.html
- src/app/core/entity-components/entity-list/entity-list.component.html
- src/app/core/entity-components/entity-list/entity-list.component.ts
> fix: fix routing into the void after opening a note in popup

- .github/workflows/master-push.yml
- .github/workflows/pull-request-update.yml
- .github/workflows/tagged-commit.yml
- build/Dockerfile
> Workflow updates

- src/app/features/matching-entities/matching-entities/matching-entities.component.ts
> fix: having multiple distance columns in matching view is supported

- src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.ts
- src/app/child-dev-project/notes/model/note.ts
- src/app/core/config/config-fix.ts
- src/app/core/entity-components/entity-select/entity-select.module.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.spec.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.ts
- src/app/core/entity/model/entity.ts
- src/app/features/matching-entities/matching-entities/matching-entities.component.html
- src/app/features/matching-entities/matching-entities/matching-entities.component.ts
- src/assets/locale/messages.de.xlf
- src/assets/locale/messages.fr.xlf
- src/assets/locale/messages.it.xlf
- src/assets/locale/messages.xlf
> Release 3.15.1

- src/app/core/user/user-security/user-security.component.html
- src/app/core/user/user-security/user-security.component.ts
- src/app/core/user/user-security/user-security.stories.ts
- src/app/core/user/user.module.ts
- src/app/utils/storybook-base.module.ts
> fix: edit buttons are not shown when user is not yet activated

- src/app/features/location/edit-location/edit-location.component.spec.ts
- src/app/features/location/edit-location/edit-location.component.ts
- src/app/features/location/geo.service.spec.ts
- src/app/features/location/geo.service.ts
- src/app/features/location/map-popup/map-popup.component.html
- src/app/features/location/map-popup/map-popup.component.ts
- src/app/features/location/map/map.component.ts
> Map improvements

- src/app/core/latest-changes/latest-changes.module.ts
- src/app/core/latest-changes/update-manager.service.ts
> fix: user is notified about unrecoverable app states

- src/app/core/entity-components/entity-list/entity-list.component.html
- src/app/core/entity-components/entity-list/entity-list.component.spec.ts
- src/app/core/entity-components/entity-list/entity-list.component.ts
make behavior of popup clickMode and config via @Input() consistent with standard behavior to be used for TodoList and others
> fix: more consistent and reusable entity-list component

- src/app/child-dev-project/schools/activities-overview/activities-overview.component.html
- src/app/core/entity-components/entity-list/EntityListConfig.ts
- src/app/core/entity-components/entity-list/entity-list.component.html
- src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.spec.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.ts
- src/app/core/ui/search/search.component.spec.ts
- src/app/core/ui/search/search.component.ts
and small cleanups (see commit messages); consider merging as rebase instead of squashed
> Allow configuration of initial list sorting

- src/app/child-dev-project/notes/dashboard-widgets/important-notes-dashboard/important-notes-dashboard.component.html
- src/app/child-dev-project/notes/dashboard-widgets/important-notes-dashboard/important-notes-dashboard.component.scss
- src/app/child-dev-project/notes/dashboard-widgets/important-notes-dashboard/important-notes-dashboard.component.spec.ts
- src/app/child-dev-project/notes/dashboard-widgets/important-notes-dashboard/important-notes-dashboard.component.ts
- src/app/core/dashboard/dashboard-list-widget/dashboard-list-widget.component.html
- src/app/core/dashboard/dashboard-list-widget/dashboard-list-widget.component.scss
- src/app/core/dashboard/dashboard-list-widget/dashboard-list-widget.component.spec.ts
- src/app/core/dashboard/dashboard-list-widget/dashboard-list-widget.component.ts
- src/app/core/dashboard/dashboard.module.ts
- src/app/core/entity/model/entity-update.ts
- src/app/core/view/fa-dynamic-icon/fa-dynamic-icon.component.ts
to more easily create new widgets that show a table of entries
> refactor: add generic dashboard-list-widget.component

- src/app/core/latest-changes/changelog.ts
- src/app/core/latest-changes/changelog/changelog.component.ts
- src/app/core/latest-changes/latest-changes.service.ts
- src/app/core/markdown-page/markdown-page.module.ts
> Fix changelog

- src/app/core/latest-changes/changelog.ts
- src/app/core/latest-changes/changelog/changelog.component.ts
- src/app/core/latest-changes/latest-changes.service.ts
- src/app/core/markdown-page/markdown-page.module.ts
> Release 3.16.1

- src/app/core/ui/ui/ui.component.html
This has already once been done in #1346 and removed in #1402 (it seemed not required any more). I now discovered that this problem actually still persists in some version, e.g. https://demo2.aam-digital.com
> fix: sidenav and main content are properly positioned

- src/app/core/ui/ui/ui.component.html
> Release 3.16.2

- src/app/features/location/map/map.component.spec.ts
- src/app/features/location/map/map.component.ts
> fix: broke circular dependency in map component

- src/app/core/config/config-fix.ts
- src/app/core/demo-data/demo-data.module.ts
- src/app/features/public-form/demo-public-form-generator.service.ts
- src/app/features/public-form/public-form.component.ts
A simple public form is available in the demo mode.
> fix(demo): added public form in demo mode

- src/app/core/entity-components/entity-utils/entity-utils.ts
- src/app/features/data-import/data-import.service.spec.ts
- src/app/features/data-import/data-import.service.ts
- src/app/features/data-import/data-import/data-import.component.ts
Array properties can be imported with CSV. Have a look at the tests to see the supported formats
see #1610
> feat(import): array properties can be imported

- src/index.html
show a more aesthetic and informative initial loading placeholder (including browser debugging details).
> fix: better initial loading screen

- angular.json
- src/app/app.module.ts
- src/app/core/config/config-fix.ts
- src/app/core/core-components.ts
- src/app/core/demo-data/demo-data.module.ts
- src/app/core/entity-components/entity-details/related-entities/related-entities.component.html
- src/app/core/entity-components/entity-details/related-entities/related-entities.component.spec.ts
- src/app/core/entity-components/entity-details/related-entities/related-entities.component.ts
- src/app/core/entity-components/entity-utils/entity-utils.ts
- src/app/core/entity/database-indexing/database-indexing.service.ts
- src/app/core/entity/entity-config.service.spec.ts
- src/app/core/entity/entity-config.service.ts
- src/app/core/ui/ui/ui.component.html
- src/app/core/ui/ui/ui.component.scss
- src/app/features/data-import/data-import.service.spec.ts
- src/app/features/data-import/data-import.service.ts
- src/app/features/data-import/data-import/data-import.component.ts
- src/app/features/public-form/demo-public-form-generator.service.ts
- src/app/features/public-form/public-form.component.ts
- src/index.html
- src/manifest.webmanifest
> Release 3.17.0

- src/app/core/config/config-fix.ts
- src/app/core/confirmation-dialog/confirmation-dialog/confirmation-dialog.component.html
- src/app/core/entity-components/entity-list/filter-generator.service.ts
[please merge un-squashed via rebase]
> small fixes & improvements

- e2e/integration/MarkingChildAsDropout.cy.ts
- e2e/support/commands.ts
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.html
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.spec.ts
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.ts
- src/app/child-dev-project/schools/school-block/school-block.component.scss
- src/app/child-dev-project/schools/school-block/school-block.component.ts
- src/app/core/entity-components/entity-list/entity-list.component.html
- src/app/core/entity-components/entity-list/entity-list.component.ts
- src/app/core/entity-components/entity-select/display-entity/display-entity.component.scss
- src/app/features/matching-entities/matching-entities/matching-entities.component.spec.ts
- src/styles/resets/_mat-chip.scss
> Scrollbar fixes

- src/app/core/entity-components/entity-list/filter-generator.service.spec.ts
- src/app/core/entity-components/entity-list/filter-generator.service.ts
> fix: configurable enum filters work with enum name in additional field

- src/app/core/configurable-enum/basic-autocomplete/basic-autocomplete.component.html
- src/app/core/configurable-enum/basic-autocomplete/basic-autocomplete.component.ts
- src/app/core/ui/primary-action/primary-action.component.scss
- src/app/features/matching-entities/matching-entities/matching-entities.component.html
- src/app/features/reporting/reporting/report-row/report-row.component.html
- src/assets/locale/messages.de.xlf
- src/assets/locale/messages.fr.xlf
- src/assets/locale/messages.it.xlf
- src/assets/locale/messages.xlf
See commits.
Fixes some problems that came up in the QM review session.
> UI improvements

- src/app/core/configurable-enum/basic-autocomplete/basic-autocomplete.component.ts
> fix: cancel works correctly in autocomplete component

- proxy.conf.json
- src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.spec.ts
- src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.ts
- src/app/child-dev-project/attendance/attendance.service.spec.ts
- src/app/child-dev-project/attendance/attendance.service.ts
- src/app/child-dev-project/children/children.service.spec.ts
- src/app/child-dev-project/children/children.service.ts
- src/app/core/configurable-enum/basic-autocomplete/basic-autocomplete.component.html
- src/app/core/configurable-enum/basic-autocomplete/basic-autocomplete.component.ts
- src/app/core/export/query.service.spec.ts
- src/app/core/export/query.service.ts
- src/app/core/session/auth/auth.interceptor.spec.ts
- src/app/core/session/auth/auth.interceptor.ts
- src/app/core/session/session-service/synced-session.service.spec.ts
- src/app/core/session/session-service/synced-session.service.ts
- src/app/core/ui/primary-action/primary-action.component.scss
- src/app/features/matching-entities/matching-entities/matching-entities.component.html
- src/app/features/reporting/reporting/report-row/report-row.component.html
- src/assets/locale/messages.de.xlf
- src/assets/locale/messages.fr.xlf
- src/assets/locale/messages.it.xlf
- src/assets/locale/messages.xlf
> Release 3.18.1

- src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.spec.ts
- src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.ts
- src/app/features/todos/todo-list/todo-list.component.ts
> Todo fixes

- src/app/core/configurable-enum/basic-autocomplete/basic-autocomplete.component.html
- src/app/core/configurable-enum/basic-autocomplete/basic-autocomplete.component.ts
- src/app/core/configurable-enum/enum-dropdown/enum-dropdown.component.html
- src/app/features/data-import/data-import.service.spec.ts
- src/app/features/data-import/data-import.service.ts
- src/app/features/data-import/data-import/data-import.component.html
- src/app/features/data-import/data-import/data-import.component.spec.ts
- src/app/features/data-import/data-import/data-import.component.ts
- src/app/features/data-import/import-meta-data.type.ts
- src/app/features/matching-entities/matching-entities/matching-entities.stories.ts
> feat: link imported data to schools/activities

- e2e/integration/MarkingChildAsDropout.cy.ts
> test: improve e2e timeouts

- src/app/core/user/user-security/user-security.component.html
- src/app/core/user/user-security/user-security.component.ts
> fix: added hint when user account is disabled

- src/app/child-dev-project/attendance/model/recurring-activity.spec.ts
- src/app/child-dev-project/children/model/child.spec.ts
- src/app/child-dev-project/children/model/child.ts
- src/app/child-dev-project/schools/model/school.spec.ts
- src/app/core/entity/model/entity.spec.ts
- src/app/core/entity/model/entity.ts
- src/app/core/entity/schema/entity-schema-field.ts
- src/app/core/ui/search/search.component.spec.ts
- src/app/core/ui/search/search.component.ts
- src/app/core/ui/search/search.service.spec.ts
- src/app/core/ui/search/search.service.ts
- src/app/core/user/user.spec.ts
- src/app/features/data-import/data-import.service.spec.ts
- src/app/features/data-import/data-import.service.ts
- src/app/features/todos/model/todo.spec.ts
- src/app/utils/expect-entity-data.spec.ts
> Search improvement

- src/app/core/configurable-enum/basic-autocomplete/basic-autocomplete.component.scss
- src/app/core/configurable-enum/basic-autocomplete/basic-autocomplete.component.ts
- src/app/features/data-import/data-import/data-import.component.spec.ts
> Add option safari (and firefox?)

- src/app/app.component.spec.ts
- src/app/child-dev-project/children/children.service.ts
> fix: error when relation does not have matching child

- src/app/app.component.spec.ts
- src/app/child-dev-project/children/children.service.ts
- src/styles/variables/_colors.scss
> Release 3.19.1

- src/app/app.module.ts
- src/app/utils/database-testing.module.ts
- src/app/utils/mocked-testing.module.ts
> Release 3.19.2

- .github/workflows/pull-request-update.yml
- .github/workflows/tagged-commit.yml
- build/README.md
- doc/compodoc_sources/concepts/infrastructure.md
> ci: update docker repository

- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-photo/image-popup/image-popup.component.scss
> Set a max width value on an image

- package-lock.json
- package.json
- src/app/child-dev-project/attendance/activity-attendance-section/activity-attendance-section.component.ts
- src/app/core/core-components.ts
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-month/edit-month.component.html
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-month/edit-month.component.scss
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-month/edit-month.component.spec.ts
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-month/edit-month.component.ts
- src/app/core/entity-components/entity-utils/view-components/display-month/display-month.component.spec.ts
- src/app/core/entity-components/entity-utils/view-components/display-month/display-month.component.ts
- src/app/core/entity/schema-datatypes/datatype-month.ts
see issue: #1666 #1657 
Displaying a month can be adjusted through the schema `additional: "YYYY-MM"`.
> Edit month

- src/app/core/demo-data/demo-data.module.ts
Publishing the demo config last so the app only initialises after all other entities have been saved.
Currently, some dashboard components stay empty on first load and a refresh on school details sometimes results in a not found error.
--
> fix: demo data initialisation

- src/app/core/database/pouch-database.ts
- src/app/core/support/support/support.component.html
- src/app/core/support/support/support.component.spec.ts
- src/app/core/support/support/support.component.ts
> Debug improvements

- src/app/core/support/support/support.component.html
- src/app/core/support/support/support.component.spec.ts
- src/app/core/support/support/support.component.ts
to help us troubleshoot sync issues + allow users a backup before "Reset Application"
> fix(core): allow to download local db from support view

- src/app/core/support/support/support.component.html
- src/app/core/support/support/support.component.spec.ts
- src/app/core/support/support/support.component.ts
> Release 3.20.2

- src/app/core/latest-changes/app-version/app-version.component.html
> fix: clicking version only opens popup once

- src/app/child-dev-project/attendance/edit-attendance/edit-attendance.component.ts
> fix: attendance check doesn't fail if category is undefined

- angular.json
> build: trying to fix sporadic scss import failures breaking the build

- .github/workflows/pull-request-update.yml
- .github/workflows/semantic-release.yml
Semantic release action is failing.
> running semantic release on update

- src/app/core/entity-components/entity-select/edit-single-entity/edit-single-entity.component.html
- src/app/core/entity-components/entity-select/edit-single-entity/edit-single-entity.component.ts
- src/app/core/entity-components/entity-select/edit-text-with-autocomplete/edit-text-with-autocomplete.component.html
- src/app/core/entity-components/entity-select/edit-text-with-autocomplete/edit-text-with-autocomplete.component.ts
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-boolean/edit-boolean.component.html
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-boolean/edit-boolean.component.ts
- src/app/features/file/edit-file/edit-file.component.html
- src/app/features/file/edit-file/edit-file.component.ts
- src/app/features/location/edit-location/edit-location.component.html
- src/app/features/location/edit-location/edit-location.component.ts
- src/app/features/todos/recurring-interval/edit-recurring-interval/edit-recurring-interval.component.html
- src/app/features/todos/recurring-interval/edit-recurring-interval/edit-recurring-interval.component.ts
> fix: added error hint component to all inputs

- README.md
Basic details on the configurability and architecture for the README as the first thing people usually look at.
> extend readme with architecture

- src/app/child-dev-project/notes/note-details/note-details.component.spec.ts
- src/app/core/config/testing-config-service.ts
- src/app/core/entity-components/entity-list/filter-generator.service.spec.ts
- src/app/core/form-dialog/dialog-buttons/dialog-buttons.component.spec.ts
- src/app/features/progress-dashboard-widget/progress-dashboard/progress-dashboard.component.spec.ts
- src/app/features/public-form/public-form.component.spec.ts
> test: fixed flaky tests

- src/app/core/pwa-install/pwa-install.component.html
- src/app/core/pwa-install/pwa-install.component.spec.ts
- src/app/core/pwa-install/pwa-install.component.ts
> fix: pwa button is visible

- src/app/child-dev-project/notes/note-details/note-details.component.spec.ts
- src/app/core/config/testing-config-service.ts
- src/app/core/entity-components/entity-list/filter-generator.service.spec.ts
- src/app/core/form-dialog/dialog-buttons/dialog-buttons.component.spec.ts
- src/app/core/pwa-install/pwa-install.component.html
- src/app/core/pwa-install/pwa-install.component.spec.ts
- src/app/core/pwa-install/pwa-install.component.ts
- src/app/features/progress-dashboard-widget/progress-dashboard/progress-dashboard.component.spec.ts
- src/app/features/public-form/public-form.component.spec.ts
> Release 3.21.2

- src/app/core/entity-components/entity-form/entity-form/entity-form.component.spec.ts
- src/app/core/entity-components/entity-form/entity-form/entity-form.component.ts
> Release 3.21.3

- e2e/integration/RecordingAttendanceOfChild.cy.ts
- e2e/support/commands.ts
> test: fixed issue with attendance e2e test

- .github/workflows/master-push.yml
- .github/workflows/percy.yml
- .github/workflows/pull-request-update.yml
Otherwise we will quickly reach the free usage limit.
> ci: skipping percy on draft PRs

- .github/workflows/semantic-release.yml
- .releaserc
> ci: fix semantic release workflow

- .github/workflows/semantic-release.yml
- .releaserc
> Semantic update

- src/app/core/common-components/help-button/help-button.component.html
- src/app/core/common-components/help-button/help-button.component.spec.ts
- src/app/core/common-components/help-button/help-button.component.ts
- src/app/core/common-components/help-button/help-button.stories.ts
- src/app/core/entity-components/entity-form/entity-form/entity-form.component.html
- src/app/core/entity-components/entity-form/entity-form/entity-form.component.ts
making the (?) tooltip button a reusable "display component".
> feat(core): help-button for consistent UI of contextual explanations

- src/app/core/config/config-fix.ts
- src/app/core/core-components.ts
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-description-only/edit-description-only.component.spec.ts
- src/app/core/entity-components/entity-utils/dynamic-form-components/edit-description-only/edit-description-only.component.ts
> feat(core): EditDescriptionOnly field to display additional text in forms

- src/app/core/config/config-fix.ts
- src/app/core/entity-components/entity-list/filter-generator.service.ts
- src/app/core/entity-components/entity-subrecord/row-details/row-details.component.ts
> small bugfixes

- src/app/core/configurable-enum/enum-dropdown/enum-dropdown.component.spec.ts
- src/app/core/configurable-enum/enum-dropdown/enum-dropdown.component.ts
> fix(forms): clear dropdown value in field after deleting its option

- src/app/core/entity-components/entity-details/related-entities/related-entities.component.html
- src/app/core/entity-components/entity-details/related-entities/related-entities.component.spec.ts
- src/app/core/entity-components/entity-details/related-entities/related-entities.component.ts
and add typing
-> in preparation for using this as super class of a new generic component
> fix(core): add loading indicator to related-entities component

- src/app/child-dev-project/attendance/edit-attendance/edit-attendance.component.html
- src/app/child-dev-project/attendance/edit-attendance/edit-attendance.component.spec.ts
- src/app/child-dev-project/attendance/edit-attendance/edit-attendance.component.ts
> fix(attendance): editing attendance in details view now enables save button

- src/app/core/entity/schema/default.datatype.ts
- src/app/features/todos/model/todo-completion.ts
- src/app/features/todos/todos-dashboard/todos-dashboard.component.spec.ts
> fix(todos): correctly load type for completion property

- src/app/child-dev-project/notes/notes-related-to-entity/notes-related-to-entity.component.html
- src/app/child-dev-project/notes/notes-related-to-entity/notes-related-to-entity.component.ts
- src/app/features/todos/todos-related-to-entity/todos-related-to-entity.component.html
- src/app/features/todos/todos-related-to-entity/todos-related-to-entity.component.ts
> fix(*): show loading indicator for note and todo lists in details view

- .storybook/main.js
> ci: removed storybook `storyStoreV7` disable

- src/app/core/config/config-fix.ts
- src/app/core/entity-list/entity-list/entity-list.component.html
- src/app/core/pwa-install/pwa-install.component.html
- src/app/core/pwa-install/pwa-install.component.scss
- src/app/core/ui/navigation/navigation/navigation.component.html
- src/app/core/ui/ui/ui.component.html
- src/app/core/ui/ui/ui.component.scss
- src/styles/variables/_colors.scss
> Design tuning

- src/app/core/entity-details/form/form.component.scss
using similar approach to import-component stepper buttons
closes #1917
> fix(forms): make "cancel" button better visible with background

- src/app/features/file/edit-file/edit-file.component.html
- src/app/features/file/edit-file/edit-file.component.scss
- src/app/features/file/edit-file/edit-file.component.spec.ts
- src/app/features/file/edit-file/edit-file.component.ts
- src/app/features/file/edit-file/edit-file.stories.ts
> fix(forms): open file attachments correctly

- e2e/integration/RecordingAttendanceOfChild.cy.ts
> test: record attendance e2e test is more stable

- src/app/child-dev-project/children/children-list/children-list.component.spec.ts
- src/app/core/entity-list/EntityListConfig.ts
- src/app/core/entity-list/entity-list/entity-list.component.html
- src/app/core/entity-list/entity-list/entity-list.component.spec.ts
- src/app/core/entity-list/entity-list/entity-list.component.ts
> fix: entity list works with new input configs

- src/app/core/entity-details/entity-details/entity-details.component.ts
Go to Children List and click add new. Console shows deprecation warning.
> fix: panels are only initialized once

- src/app/core/config/config-fix.ts
as templates for client setups
using school name in children export and attendance report
> fix(demo): extended some default configs for reports and exports 

- src/app/child-dev-project/notes/model/note.ts
- src/app/child-dev-project/notes/note-details/note-details.component.ts
- src/app/core/config/config-fix.ts
- src/app/features/file/edit-file/edit-file.component.ts
> fix: notes have attachments

- src/app/core/common-components/entity-subrecord/entity-subrecord/entity-subrecord.component.ts
for special subrecord tables like AserComponent
> fix(core): correctly init columns in subrecord component

- src/app/core/permissions/ability/ability.service.spec.ts
- src/app/core/permissions/ability/ability.service.ts
> fix: deleted rules object does not throw error

- src/app/core/permissions/permission-enforcer/permission-enforcer.service.ts
- src/app/core/session/login/login.component.spec.ts
- src/app/core/session/login/login.component.ts
- src/app/core/session/session.module.ts
> Release 3.27.1

- src/app/core/admin/admin-entity-details/admin-entity-form/admin-entity-form.component.html
- src/app/core/admin/admin-entity-details/admin-entity-form/admin-entity-form.component.scss
- src/app/core/admin/admin-entity-details/admin-entity-form/admin-entity-form.component.spec.ts
- src/app/core/admin/admin-entity-details/admin-entity-form/admin-entity-form.component.ts
- src/app/core/admin/admin-entity-details/admin-entity/admin-entity-details.component.ts
- src/app/core/entity/entity-actions/entity-actions.service.ts
> Admin UI fixes

- src/app/core/ui/navigation/navigation/navigation.component.ts
> fix: highlight active menu item again

- src/app/core/basic-datatypes/entity-array/edit-entity-array/entity-reference-array.stories.ts
- src/app/core/basic-datatypes/entity/edit-single-entity/entity-reference.stories.ts
- src/app/core/entity-details/entity-details/entity-details.stories.ts
- src/app/core/entity/default-datatype/edit-component-story-utils.ts
- src/app/utils/storybook-base.module.ts
> test: storybook stories do not try to log in

- src/app/core/session/auth/keycloak/keycloak-auth.service.ts
- src/app/features/todos/todos-dashboard/todos-dashboard.component.ts
- src/main.ts
fixes https://aam-digital.sentry.io/issues/4868382000/events/d6bb605fa48f4c9681a878938e7f062d/
and https://aam-digital.sentry.io/issues/4792457271/events/e7209269af1442e1827997e39eab1eab/
> fix: ... of undefined errors

- src/app/child-dev-project/children/health-checkup/health-checkup-component/health-checkup.component.html
- src/app/child-dev-project/children/health-checkup/health-checkup-component/health-checkup.component.ts
- src/app/core/config/config-fix.ts
- src/app/features/historical-data/historical-data/historical-data.component.spec.ts
- src/app/features/historical-data/historical-data/historical-data.component.ts
> fix: show new health an observation records immediately

- src/app/core/basic-datatypes/configurable-enum/configurable-enum-datatype/configurable-enum.datatype.spec.ts
- src/app/core/basic-datatypes/configurable-enum/configurable-enum-datatype/configurable-enum.datatype.ts
- src/app/core/basic-datatypes/discrete/discrete-import-config/discrete-import-config.component.html
- src/app/core/import/import.service.spec.ts
- src/app/core/import/import.service.ts
> Fix some import module bugs

- src/app/core/permissions/ability/ability.service.spec.ts
- src/app/core/permissions/ability/ability.service.ts
> fix(permissions): correctly interpolate user.name again

- src/app/core/common-components/entity-form/entity-form.service.ts
- src/app/core/common-components/entity-form/entity-form/entity-form.component.spec.ts
- src/app/core/permissions/ability/entity-ability.ts
- src/app/features/dashboard-widgets/birthday-dashboard-widget/birthday-dashboard/birthday-dashboard.component.spec.ts
> fix: display form correctly when creating new with permission conditions

- src/app/child-dev-project/notes/notes-manager/notes-manager.component.spec.ts
- src/app/child-dev-project/notes/notes-manager/notes-manager.component.ts
- src/app/core/basic-datatypes/date/date-range-filter/date-range-filter.component.html
- src/app/core/basic-datatypes/date/date-range-filter/date-range-filter.component.spec.ts
- src/app/core/basic-datatypes/date/date-range-filter/date-range-filter.component.ts
- src/app/core/filter/filter/filter.component.html
- src/app/core/filter/filter/filter.component.ts
- src/app/core/filter/filters/dateFilter.ts
- src/app/core/filter/filters/filters.ts
- src/app/core/filter/list-filter/list-filter.component.html
- src/app/core/filter/list-filter/list-filter.component.ts
and refactoring of filter-component
closes: #2292
> fix(filter): date-range filter available for any field

- src/app/core/config/config-fix.ts
- src/app/core/filter/filters/filters.spec.ts
- src/app/core/filter/filters/filters.ts
> fix(filter): support filters on number fields

- src/app/core/session/auth/keycloak/keycloak-auth.service.spec.ts
- src/app/core/session/auth/keycloak/keycloak-auth.service.ts
partial revert of PR #2314 
in dev the updateToken call seems to return something while prod instances do not have a return value
> avoid updateToken abort

- src/app/core/filter/list-filter/list-filter.component.html
- src/app/core/filter/list-filter/list-filter.component.ts
> fix(filter): correctly display default filter value

- src/app/core/admin/admin-entity-details/admin-entity-field/admin-entity-field.component.spec.ts
- src/app/core/admin/admin-entity-details/admin-entity-field/admin-entity-field.component.ts
> fix(Admin UI): generate manual dropdown category id without errors

- src/app/core/admin/admin-entity-details/admin-entity-details/admin-entity-details.component.spec.ts
- src/app/core/admin/admin-entity-list/admin-entity-list.component.ts
- src/app/core/admin/admin-entity/admin-entity.component.spec.ts
- src/app/core/admin/admin-entity/admin-entity.component.ts
- src/app/core/config/config-fix.ts
- src/app/core/config/config.service.ts
- src/app/core/entity-details/EntityDetailsConfig.ts
- src/app/core/entity-details/entity-details/entity-details.component.spec.ts
- src/app/core/entity-details/entity-details/entity-details.component.ts
- src/app/core/entity-details/entity-details/entity-details.stories.ts
- src/app/core/entity-list/EntityListConfig.ts
- src/app/core/entity-list/entity-list/entity-list.component.spec.ts
- src/app/core/entity-list/entity-list/entity-list.component.ts
- src/app/features/config-setup/config-import-parser.service.spec.ts
- src/app/features/config-setup/config-import-parser.service.ts
for clarity and future developments
(extracted from PR #2304 for easier review)
> refactor(config): rename entity to entityType in config

- src/app/core/admin/building-blocks/admin-tabs/admin-tabs.component.html
- src/app/core/admin/building-blocks/admin-tabs/admin-tabs.component.spec.ts
- src/app/core/admin/building-blocks/admin-tabs/admin-tabs.component.ts
> Admin UI: tab name changes not saved anymore #2347

- src/app/features/reporting/sql-report/sql-report.service.spec.ts
> test: disable sql-report tests

- src/app/core/common-components/basic-autocomplete/basic-autocomplete.component.ts
that already has value
(regression for single-select fields)
> fix(forms): show all dropdown options when clicking into field 

- src/app/core/common-components/entities-table/entities-table.component.ts
> fix: default date filter not applied on mobile devices

- src/app/core/entity-details/related-entities/related-entities.component.html
- src/app/core/entity-details/related-entities/related-entities.component.ts
- src/app/core/form-dialog/row-details/row-details.component.ts
> Fix popup form navigation to details

- src/app/core/filter/filter-generator/filter-generator.service.ts
> fix: use short label for filters of list

- src/app/core/basic-datatypes/configurable-enum/configurable-enum-datatype/configurable-enum.datatype.spec.ts
- src/app/core/basic-datatypes/discrete/discrete.datatype.ts
- src/app/core/entity/default-datatype/default.datatype.ts
> fix: correctly map multi values during import

- src/app/core/admin/admin-entity-details/admin-entity-field/admin-entity-field.component.ts
- src/app/core/admin/admin-entity-details/admin-entity-field/configure-entity-field-validator/configure-entity-field-validator.component.spec.ts
- src/app/core/admin/admin-entity-details/admin-entity-field/configure-entity-field-validator/configure-entity-field-validator.component.ts
fixes #2424
also, Output object was wrongly typed.
> fix(Admin UI): only save active validator configs

- src/app/core/ui/navigation/navigation/navigation.component.html
- src/app/core/ui/navigation/navigation/navigation.component.scss
- src/app/features/dashboard-widgets/shortcut-dashboard-widget/shortcut-dashboard/shortcut-dashboard.component.html
- src/app/features/dashboard-widgets/shortcut-dashboard-widget/shortcut-dashboard/shortcut-dashboard.component.scss
> fix: enable menu and shortcut items to be copied or opened in tab

- src/app/app.component.ts
- src/app/core/admin/admin-entity-types/admin-entity-types.component.html
- src/app/core/admin/admin-entity-types/admin-entity-types.component.scss
- src/app/core/admin/admin-entity-types/admin-entity-types.component.spec.ts
- src/app/core/admin/admin-entity-types/admin-entity-types.component.ts
- src/app/core/admin/admin.module.ts
- src/app/core/admin/admin.routing.ts
- src/app/core/admin/admin/admin.component.html
- src/app/core/entity/entity-config.service.ts
> feat(Admin UI): basic prototype to manage entity types

- src/app/core/session/auth/keycloak/keycloak-auth.service.ts
- src/app/core/session/auth/keycloak/remote-login-not-available.error.ts
- src/app/core/session/session-service/session-manager.service.ts
> Fix "retry online login"

- src/app/features/dashboard-widgets/progress-dashboard-widget/progress-dashboard/progress-dashboard.component.html
> Bug Fixed: Edit Button of Progress Dashboard Widget

- src/app/core/basic-datatypes/configurable-enum/configurable-enum.spec.ts
- src/app/core/basic-datatypes/configurable-enum/configurable-enum.ts
- src/app/core/basic-datatypes/configurable-enum/configure-enum-popup/configure-enum-popup.component.ts
- src/app/core/basic-datatypes/configurable-enum/enum-dropdown/enum-dropdown.component.spec.ts
- src/app/core/basic-datatypes/configurable-enum/enum-dropdown/enum-dropdown.component.ts
> fix: prevent invalid dropdown options to be added

- src/app/core/dashboard/dashboard/dashboard.component.spec.ts
- src/app/core/demo-data/demo-data-initializer.service.spec.ts
- src/app/core/demo-data/demo-data-initializer.service.ts
- src/app/core/logging/logging.service.ts
- src/app/core/permissions/ability/ability.service.spec.ts
- src/app/core/permissions/permission-enforcer/permission-enforcer.service.ts
- src/app/core/permissions/permission-guard/user-role.guard.spec.ts
- src/app/core/session/auth/keycloak/account-page/account-page.component.spec.ts
- src/app/core/session/auth/keycloak/keycloak-auth.service.spec.ts
- src/app/core/session/auth/keycloak/keycloak-auth.service.ts
- src/app/core/session/auth/local/local-auth.service.spec.ts
- src/app/core/session/auth/session-info.ts
- src/app/core/session/login/login.component.spec.ts
- src/app/core/session/session-service/session-manager.service.spec.ts
- src/app/core/session/session-service/session-manager.service.ts
- src/app/core/support/support/support.component.html
- src/app/core/support/support/support.component.spec.ts
- src/app/core/support/support/support.component.ts
- src/app/core/user/user-account/user-account.component.html
- src/app/core/user/user-account/user-account.component.ts
- src/app/core/user/user-security/user-security.component.spec.ts
- src/app/core/user/user-security/user-security.component.ts
- src/app/core/user/user-security/user-security.stories.ts
- src/app/utils/mocked-testing.module.ts
> improvements for users without linked entity

- .github/workflows/pull-request-closed.yml
> ci: fix cache clean up

- src/app/child-dev-project/notes/dashboard-widgets/notes-dashboard/notes-dashboard.component.spec.ts
- src/app/core/admin/admin-entity-details/admin-entity-form/admin-entity-form.component.spec.ts
- src/app/core/database/sync.service.spec.ts
- src/app/core/database/sync.service.ts
See #https://github.com/Aam-Digital/internal/issues/58
> fix: liveSync just starts one sync job at a time

- src/app/core/config/config-fix.ts
- src/app/features/file/edit-file/edit-file.component.html
- src/app/features/file/edit-file/edit-file.component.spec.ts
- src/app/features/file/edit-file/edit-file.component.ts
- src/app/features/file/edit-photo/edit-photo.component.html
- src/app/features/file/edit-photo/edit-photo.component.ts
- src/app/features/file/file.datatype.ts
related to PDF Feature's template selection
> fix: make acceptable file types for attachments configurable

- package-lock.json
- package.json
- src/app/child-dev-project/attendance/attendance-manager/attendance-manager.component.scss
- src/app/core/common-components/entities-table/list-paginator/list-paginator.component.scss
- src/app/core/dashboard/dashboard/dashboard.component.scss
- src/app/core/ui/ui/ui.component.scss
- src/app/features/dashboard-widgets/progress-dashboard-widget/edit-progress-dashboard/edit-progress-dashboard.component.scss
- src/assets/locale/messages.de.xlf
- src/assets/locale/messages.fr.xlf
- src/assets/locale/messages.it.xlf
- src/assets/locale/messages.xlf
- src/bootstrap-i18n.ts
- src/index.html
- src/styles/mixins/_grid-layout.scss
> fix(i18n): fix problems with translations

- .github/workflows/pull-request-update-or-push-tag.yml
- build/Dockerfile
> fix: app loading (because of service-worker hash)

- src/app/child-dev-project/attendance/activity-attendance-section/activity-attendance-section.component.ts
- src/app/child-dev-project/children/child-details/grouped-child-attendance/grouped-child-attendance.component.html
- src/app/child-dev-project/children/child-details/grouped-child-attendance/grouped-child-attendance.component.ts
> Attendance Overview tab in Child Details should hide archived 

- src/app/core/config/migrate-add-entity-attributes.ts
- src/app/core/database/pouch-database.ts
- src/app/features/template-export/template-export.entity.ts
see commits
please merge unsquashed
> Fix various small issues

- src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-week-dashboard.component.spec.ts
- src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-week-dashboard.component.ts
- src/app/child-dev-project/attendance/model/activity-attendance.ts
> fix(attendance): display absent participants even if added via group

- src/app/core/dashboard/dashboard-list-widget/dashboard-list-widget.component.html
- src/app/core/dashboard/dashboard-list-widget/dashboard-list-widget.component.ts
- src/app/features/dashboard-widgets/entity-count-dashboard-widget/entity-count-dashboard/entity-count-dashboard.component.html
- src/app/features/dashboard-widgets/entity-count-dashboard-widget/entity-count-dashboard/entity-count-dashboard.component.scss
- src/app/features/dashboard-widgets/entity-count-dashboard-widget/entity-count-dashboard/entity-count-dashboard.component.ts
- src/app/features/dashboard-widgets/entity-count-dashboard-widget/entity-count-dashboard/entity-count-dashboard.stories.ts
> Fixed the glitches.

- src/app/child-dev-project/attendance/edit-attendance/edit-attendance.component.html
- src/app/child-dev-project/attendance/edit-attendance/edit-attendance.component.ts
- src/app/core/common-components/entity-select/entity-select.component.ts
> fix: attendance status sometimes not saved

- src/app/core/filter/filters/filters.ts
- src/app/features/location/location-input/location-input.component.ts
- src/app/features/location/map-popup/map-popup.component.ts
> fix: the bug edit location dialog save button not reachable on mobile

- .github/workflows/pull-request-update-or-push-tag.yml
- src/app/core/common-components/entity-form/entity-form.service.spec.ts
- src/app/core/common-components/entity-form/entity-form.service.ts
- src/app/core/permissions/ability/ability.service.ts
- src/app/core/ui/navigation/menu-item/menu-item.component.html
- src/app/core/ui/navigation/menu-item/menu-item.component.scss
- src/app/features/public-form/public-form.component.ts
> Release 3.43.1

- doc/compodoc_sources/how-to-guides/create-new-datatype.md
@Abhinegi2 , added some details how to implement custom datatypes here
> doc: add details about custom EditComponent implementations

- src/app/core/admin/admin-entity-details/admin-entity-form/admin-entity-form.component.html
- src/app/core/admin/admin-entity-details/admin-entity-form/admin-entity-form.component.ts
- src/app/core/admin/admin-entity/admin-entity.component.ts
closes: [#2756](https://github.com/Aam-Digital/ndb-core/issues/2756)
> field-group titles fixes

- README.md
> [Feat]: Added the translation languages badges in README

- src/app/features/public-form/public-form.component.scss
closes: [#2776](https://github.com/Aam-Digital/ndb-core/issues/2776)
> image in Public Form may get distorted

- src/app/core/admin/admin-entity-details/admin-entity-form/admin-entity-form.component.ts
> fix(Admin UI): keep the focus when changing field group titles

- src/app/core/common-components/entities-table/value-accessor/value-accessor.ts
- src/app/core/export/download-service/download.service.spec.ts
> fix(Export): display address text for "location" fields in csv exports

- src/app/features/public-form/edit-publicform-route/edit-publicform-route.component.html
- src/app/features/public-form/edit-publicform-route/edit-publicform-route.component.scss
- src/app/features/public-form/edit-publicform-route/edit-publicform-route.component.spec.ts
- src/app/features/public-form/edit-publicform-route/edit-publicform-route.component.ts
- src/app/features/public-form/public-form-config.ts
- src/app/features/public-form/public-form.module.ts
> easier way to copy the link to the form (add some button?)

- src/app/core/entity/database-entity.decorator.ts
- src/app/core/import/import-column-mapping/import-column-mapping.component.html
- src/app/core/import/import-entity-type/import-entity-type.component.spec.ts
closes: [#2819](https://github.com/Aam-Digital/ndb-core/issues/2819)
> feat(Import): Update entity type in import column mapping component

- src/app/core/config/config-fix.ts
- src/app/core/default-values/default-value.service.spec.ts
- src/app/core/default-values/default-value.service.ts
- src/app/core/default-values/dynamic-placeholder-value.service.spec.ts
- src/app/core/default-values/inherited-value.service.spec.ts
- src/app/core/entity/schema/default-value-config.ts
- src/app/features/public-form/public-form.component.spec.ts
> defaultValue for configurable-enum dropdowns

- src/app/core/common-components/basic-autocomplete/basic-autocomplete.component.ts
> Multiple dropdown values are selected, but not being displayed.

- src/app/features/reporting/reporting/reporting.component.html
- src/app/features/reporting/reporting/reporting.component.ts
>  display report calculation time in local timezone

- src/app/core/admin/admin-entity/admin-entity-general-settings/admin-entity-general-settings.component.ts
- src/app/core/entity/model/entity.spec.ts
- src/app/core/entity/model/entity.ts
> Make dropdown (configurable-enum) fields usable in Entity title (toStringAttributes) 

- src/app/core/entity-list/entity-list/entity-list.component.spec.ts
- src/app/core/entity-list/entity-list/entity-list.component.ts
> Admin UI for List View uses non-existant "default" columnGroup

- src/app/core/admin/admin-entity-details/admin-entity-field/admin-entity-field.component.html
- src/app/core/admin/admin-entity-details/admin-entity-field/admin-entity-field.component.ts
- src/app/utils/generate-id-from-label/generate-id-from-label.spec.ts
- src/app/utils/generate-id-from-label/generate-id-from-label.ts
> Fields seem to cause errors if the "Field ID" includes a "."?

- src/app/core/basic-datatypes/entity/entity-block/entity-block.component.html
- src/app/core/basic-datatypes/entity/entity-block/entity-block.component.ts
- src/app/core/common-components/template-tooltip/template-tooltip.directive.ts
to prevent performance issues when using the app for longer time
see https://github.com/Aam-Digital/internal/issues/131
> fix: properly release overlay of templated tooltips

- src/app/features/de-duplication/bulk-merge-records/bulk-merge-records.component.html
- src/app/features/de-duplication/bulk-merge-records/bulk-merge-records.component.ts
>  Merge records: Multiple selected from from a list

- src/app/core/entity-list/duplicate-records/duplicate-records.service.spec.ts
- src/app/core/entity-list/duplicate-records/duplicate-records.service.ts
- src/app/core/entity/entity-actions/entity-actions.service.ts
closes: #2595
- I added a duplicate action in the details view.
- Also added a success message while duplicating records
> "Duplicate" should also be available as Entity Action from EntityDetails menu 

- src/app/core/admin/admin-entity-details/admin-entity-field/admin-entity-field.component.html
- src/app/core/admin/admin-entity-details/admin-entity-field/admin-entity-field.component.ts
>  refactor other components that do not yet use EditEntityTypeDropdown #2699

- src/app/core/admin/admin-entity-details/admin-entity-details/admin-entity-details.component.html
- src/app/core/admin/admin-entity-details/admin-entity-form/admin-entity-form.component.html
- src/app/core/admin/admin-entity-details/admin-entity-form/admin-entity-form.component.ts
- src/app/core/admin/building-blocks/admin-tabs/admin-tabs.component.html
closes: [#2940](https://github.com/Aam-Digital/ndb-core/issues/2940)
>  Admin UI cannot create new field group in completely new section/tab

- .github/workflows/pull-request-update-or-push-tag.yml
- src/app/core/common-components/basic-autocomplete/basic-autocomplete.component.ts
> Admin UI: "Edit Field" type should allow typing to filter the dropdown options

- src/app/core/admin/admin-entity-details/admin-entity-field/admin-entity-field.component.ts
- src/app/core/admin/admin-entity-details/admin-entity-field/default-value-options/default-value-options.component.html
- src/app/core/admin/admin-entity-details/admin-entity-field/default-value-options/default-value-options.component.spec.ts
- src/app/core/admin/admin-entity-details/admin-entity-field/default-value-options/default-value-options.component.ts
- src/app/core/common-components/entity-field-edit/entity-field-edit.component.ts
- src/app/core/config/config.service.spec.ts
- src/app/core/config/config.service.ts
- src/app/core/default-values/default-value-strategy.interface.ts
- src/app/core/default-values/default-value.service.spec.ts
- src/app/core/default-values/default-value.service.ts
- src/app/core/default-values/inherited-value.service.spec.ts
- src/app/core/default-values/inherited-value.service.ts
- src/app/core/entity/schema/default-value-config.ts
> Refactor to improve DefaultValue code

- src/app/core/entity-list/entity-list/entity-list.component.html
- src/app/core/filter/filter/filter.component.html
- src/app/core/filter/filter/filter.component.ts
> "Clear all filters" button for lists 

- src/app/core/import/column-mapping.ts
- src/app/core/import/import-column-mapping/edit-import-column-mapping/edit-import-column-mapping.component.ts
- src/app/core/import/import-column-mapping/import-column-mapping.service.ts
>  Auto-mapped columns during import cannot be reset 

- src/app/features/automated-status-update/automated-status-update-config-service.ts
closes: [#2982](https://github.com/Aam-Digital/ndb-core/issues/2982)
> auto-update: when two related entities are updated, one change is not saved

- .github/workflows/on-master-push.yml
- .github/workflows/pull-request-update-or-push-tag.yml
- build/Dockerfile
> Don’t run unit test in docker container in CI

- .github/workflows/_qa.yaml
- .github/workflows/on-master-push.yml
- .github/workflows/pull-request-update-or-push-tag.yml
Extract QA into a separate workflow and call it on master, tag and PR builds.
> refactor: Extract QA CI workflow

- src/environments/environment.prod.ts
- src/main.ts
> fix: set sentry logging environment

- src/app/core/config/config.service.ts
- src/app/core/default-values/default-value-service/default-value.service.ts
- src/app/features/public-form/public-form.component.ts
> Public Forms not backward compatible with old defaultValue config

- src/app/core/config/config.service.ts
- src/app/features/public-form/public-form.component.ts
> Public Form: n.getId is not a function

- src/app/core/common-components/entity-form/entity-form/entity-form.component.scss
> Fields should have a max width

- .github/workflows/on-master-push.yml
> fix(ci): Upload screenshots on master branch build

- src/app/core/user/user-admin-service/keycloak-admin.service.ts
>  Unexpected error from UserAdminService 

- src/app/core/admin/admin-entity-types/admin-entity-types.component.ts
- src/app/core/basic-datatypes/configurable-enum/configurable-enum.ts
- src/app/core/config/config.ts
- src/app/core/entity-details/entity-details/entity-details.component.html
- src/app/core/entity-list/entity-list/entity-list.component.html
- src/app/core/entity/model/entity.ts
- src/app/core/import/import-metadata.ts
- src/app/core/site-settings/site-settings.ts
- src/app/features/dashboard-widgets/progress-dashboard-widget/progress-dashboard/progress-dashboard-config.ts
- src/app/features/notification/model/notification-config.ts
- src/app/features/notification/model/notification-event.ts
- src/app/features/public-form/public-form-config.ts
- src/app/features/reporting/report-config.ts
- src/app/features/template-export/template-export.entity.ts
>  Public form become blank on editing the label. 

- src/app/core/basic-datatypes/configurable-enum/configurable-enum-testing.ts
- src/app/core/basic-datatypes/configurable-enum/demo-configurable-enum-generator.service.ts
- src/app/core/basic-datatypes/configurable-enum/demo-enums.ts
- src/app/core/config/config-fix.ts
- src/app/core/config/default-config/default-activity-status.ts
- see #2976
added some additional field and config to standard demo to demonstrate the new feature
> fix(demo): add default config for auto-update rule

- src/app/core/common-components/entity-form/entity-form/entity-form.component.scss
> fix: correctly use full available width for form field again

- src/app/core/admin/admin-menu/admin-menu-list/admin-menu-list.component.html
- src/app/core/admin/admin-menu/admin-menu-list/admin-menu-list.component.scss
- src/app/core/admin/admin-menu/admin-menu-list/admin-menu-list.component.ts
- src/app/core/admin/admin-menu/admin-menu.component.html
- src/app/core/admin/admin-menu/admin-menu.component.ts
- src/app/core/ui/navigation/menu-item.ts
- src/app/core/ui/navigation/menu-item/menu-item.component.html
- src/app/core/ui/navigation/menu-item/menu-item.component.ts
- src/index.html
> feat: drag & drop - Configure Navigation Menu 

- src/app/core/ui/primary-action/primary-action.component.scss
- src/app/core/ui/ui/ui.component.html
- src/app/core/ui/ui/ui.component.scss
> fix: Make viewport scroll container

- src/app/app.component.ts
- src/app/core/setup/context-aware-dialog/context-aware-dialog.component.html
- src/app/core/setup/context-aware-dialog/context-aware-dialog.component.scss
- src/app/core/setup/context-aware-dialog/context-aware-dialog.component.spec.ts
- src/app/core/setup/context-aware-dialog/context-aware-dialog.component.ts
- src/app/core/setup/demo-assistance-dialog/demo-assistance-dialog.component.html
- src/app/core/setup/demo-assistance-dialog/demo-assistance-dialog.component.scss
- src/app/core/setup/demo-assistance-dialog/demo-assistance-dialog.component.spec.ts
- src/app/core/setup/demo-assistance-dialog/demo-assistance-dialog.component.ts
- src/app/core/setup/setup.service.ts
- src/app/core/ui/ui/ui.component.html
- src/app/core/ui/ui/ui.component.ts
> Demo-Flow: Welcome and further actions 

- src/app/core/config/config-fix.ts
- src/app/core/entity-details/EntityDetailsConfig.ts
- src/app/core/entity-details/entity-details/entity-details.component.spec.ts
- src/app/core/entity-details/entity-details/entity-details.component.ts
> Hide sections without permissions #769

- src/app/core/admin/admin-entity/admin-entity-general-settings/admin-entity-general-settings.component.html
- src/app/core/admin/admin-entity/admin-entity-general-settings/admin-entity-general-settings.component.ts
- src/app/core/admin/admin-entity/admin-entity.component.spec.ts
- src/app/core/admin/admin-entity/admin-entity.component.ts
- src/app/core/config/config.service.ts
- src/app/core/entity-details/entity-details/entity-details.component.spec.ts
- src/app/core/entity-details/entity-details/entity-details.component.ts
- src/app/core/entity/entity-actions/entity-delete.service.spec.ts
- src/app/core/entity/entity-actions/entity-delete.service.ts
- src/app/core/entity/entity-config.service.ts
- src/app/core/entity/entity-config.ts
- src/app/core/entity/model/entity.ts
- src/app/core/user/user-admin-service/keycloak-admin.service.spec.ts
- src/app/core/user/user-admin-service/keycloak-admin.service.ts
> failed to delete user account 

- e2e/tests/dashboard-tests.spec.ts
- src/app/child-dev-project/attendance/activity-card/activity-card.stories.ts
- src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.stories.ts
- src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.stories.ts
- src/app/child-dev-project/children/demo-data-generators/demo-child-generator.service.ts
- src/app/child-dev-project/notes/demo-data/demo-note-generator.service.ts
- src/app/core/user/demo-user-generator.service.ts
- src/app/features/todos/model/demo-todo-generator.service.ts
- see #2995 
This change will allow us to generate demo data without depending on DI.
> refactor: Extract demo data generation into static functions

- e2e/tests/attendance-tests.spec.ts
We replace tests that don’t include actions (except for navigation) and check for static text or are fixture data dependent with screenshots.
> refactor: Simplify attendance list tests with screenshot

- src/app/core/common-components/entity-form/entity-form.service.spec.ts
- src/app/core/entity/entity-config.service.spec.ts
> EntityConfigService unit tests are failing sometime 

- doc/compodoc_sources/concepts/permissions.md
- src/app/core/user/user-security/user-security.component.spec.ts
- src/app/core/user/user-security/user-security.component.ts
> fix: correct API call to ensure resync after change of permissions

- src/app/core/admin/admin-entity-details/admin-entity-panel-component/admin-entity-panel-component.component.html
- src/app/core/admin/admin-entity-details/admin-entity-panel-component/admin-entity-panel-component.component.ts
- src/app/core/admin/admin-entity-list/admin-entity-list.component.html
- src/app/core/admin/admin-entity-list/admin-entity-list.component.ts
- src/app/core/admin/admin-list-manager/admin-list-manager.component.html
- src/app/core/admin/admin-list-manager/admin-list-manager.component.ts
- src/app/core/common-components/entity-field-label/entity-field-label.component.ts
>  app-entity-field-label component is not showing label for custom schema field

- src/app/core/language/language-select/language-select.component.spec.ts
- src/app/core/language/language-select/language-select.component.ts
- src/app/core/language/language.service.spec.ts
- src/app/core/language/language.service.ts
- src/app/core/site-settings/site-settings.service.spec.ts
- src/app/core/site-settings/site-settings.service.ts
>  Switching the language in Site Settings is not changing the UI language 

- src/app/core/common-components/entity-load/entity-load.pipe.spec.ts
- src/app/core/common-components/entity-load/entity-load.pipe.ts
- src/app/core/entity-details/entity-details/entity-details.component.html
- src/app/core/entity-details/entity-details/entity-details.component.ts
- src/app/core/entity-list/entity-list/entity-list.component.html
- src/app/core/entity-list/entity-list/entity-list.component.ts
> "edit data structure" button visible regardless of Config entity permission? 

- src/app/features/location/map-popup/map-popup.component.html
- src/app/features/location/map-popup/map-popup.component.ts
- src/app/features/location/map/map.component.ts
- src/app/features/matching-entities/matching-entities/matching-entities.component.html
> Matching Map popup should not show search box 

- e2e/tests/attendance-tests.spec.ts
- e2e/tests/dashboard-tests.spec.ts
- src/app/child-dev-project/attendance/activity-card/activity-card.stories.ts
- src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.stories.ts
- src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.stories.ts
- src/app/child-dev-project/attendance/demo-data/demo-activity-generator.service.ts
- src/app/child-dev-project/children/demo-data-generators/demo-child-generator.service.ts
Add tests for editing participants of recurring activity. Also includes a separate commit that improves fixture generation functions. This results in some of the screenshots changing
> tests:  Add tests for editing participants of recurring activity

- src/app/core/basic-datatypes/configurable-enum/configure-enum-popup/configure-enum-popup.component.html
- src/app/core/basic-datatypes/configurable-enum/configure-enum-popup/configure-enum-popup.component.ts
> Deleting a dropdown option is not immediately shown in the edit dialog 

- src/app/core/config/config.app-initializer.ts
- src/app/core/session/login/login.component.spec.ts
- src/app/core/session/login/login.component.ts
closes: https://github.com/orgs/Aam-Digital/projects/2/views/9?pane=issue&itemId=116234229&issue=Aam-Digital%7Cinternal%7C183
>  fix Open Redirect vulnerabilities 

- src/app/core/admin/admin-entity-details/admin-entity-field/configure-entity-field-validator/configure-entity-field-validator.component.html
- src/app/core/admin/admin-entity-details/admin-entity-field/configure-entity-field-validator/configure-entity-field-validator.component.spec.ts
- src/app/core/admin/admin-entity-details/admin-entity-field/configure-entity-field-validator/configure-entity-field-validator.component.ts
- src/app/core/basic-datatypes/string/display-email/display-email.component.ts
- src/app/core/basic-datatypes/string/display-email/display-email.stories.ts
- src/app/core/basic-datatypes/string/edit-email/edit-email.component.html
- src/app/core/basic-datatypes/string/edit-email/edit-email.component.spec.ts
- src/app/core/basic-datatypes/string/edit-email/edit-email.component.ts
- src/app/core/basic-datatypes/string/edit-email/edit-email.stories.ts
- src/app/core/basic-datatypes/string/email.datatype.ts
- src/app/core/common-components/entity-form/dynamic-form-validators/dynamic-validators.service.spec.ts
- src/app/core/common-components/entity-form/dynamic-form-validators/dynamic-validators.service.ts
- src/app/core/common-components/entity-form/dynamic-form-validators/form-validator-config.ts
- src/app/core/core-components.ts
- src/app/core/core.module.ts
- src/assets/base-configs/education/Config_CONFIG_ENTITY.json
> added email datatype

- .claude/commands/write-e2e-test.md
- CLAUDE.md
- doc/compodoc_sources/how-to-guides/end-to-end-tests.md
Also add some basic project memory for Claude to make working with the
codebase easier.
> Add Claude Code command for writing e2e tests

- src/app/core/common-components/confirmation-dialog/confirmation-dialog/confirmation-dialog.component.html
- src/app/core/common-components/confirmation-dialog/confirmation-dialog/confirmation-dialog.component.spec.ts
- src/app/core/common-components/confirmation-dialog/confirmation-dialog/confirmation-dialog.component.ts
> fix(core): support markdown in confirmation dialog texts

- src/app/core/admin/admin-menu/admin-menu-item/admin-menu-item.component.html
- src/app/core/admin/admin-menu/admin-menu-item/admin-menu-item.component.ts
> fix(bug) : Submenu changes should saved in the navigation menu

- src/app/core/form-dialog/dialog-buttons/dialog-buttons.component.html
- src/app/core/form-dialog/dialog-buttons/dialog-buttons.component.ts
- closes #3231
_delete things that don't apply; add any open tasks and issues_
>  Pre-Match confirmation dialog "Save" button is disabled until some of the pre-filled fields are edited 
