Aam-Digital/ndb-core

src/app/database/mock-database-manager.service.ts
src/app/latest-changes/app-version/app-version.component.ts

Plain Objects cause issues on filtering for the dashboard. The User is not set through the EntityManager and is just a plain Object, as opposed to all other objects from demo-data.ts.
This Pull Request changes the code, so the User is a real object and filtering works.
see issue: #167, #169

Fix Mock Database Filtering

---

package-lock.json
package.json
src/app/admin/admin/admin.component.ts
src/app/database/pouch-database-manager.service.ts
src/app/database/pouch-database.spec.ts
src/app/ui/search/search.component.spec.ts

PouchDB is able to run both in NodeJS as well as in a Browser. In a browser, IndexedDB will be used, for NodeJS, however, Leveldown is the backend, which needs a binary. Per default, PouchDB will install support for both scenarios, with the binary failing to install on some versions of node due to prebuilds not being available (i.e. 9, 11).
There are officially supported versions of PouchDB ("presets") that don't come with this dependency. We should use these stripped versions to have less dependencies in our project, allowing a faster and more stable npm install.
See https://pouchdb.com/custom.html for more information.

Use PouchDB Browser

---

src/app/sync-status/sync-status/sync-status.component.spec.ts

Run `npm run test`. Before this change (i.e. on master), after the tests successfully ran, the Sync Status Dialog was not closed. After this change, it is.
Adapted from 12d3e8fd5552e3449ec502548632343bca1717b8

Properly close Sync Status Dialog in tests

---

karma.conf.js
package-lock.json
package.json

To use Firefox instead of Chrome, launch karma with `ng test browsers=Firefox`
@RichardNutt, would this benefit you?

Enable running the Unit Tests in Firefox

---

src/app/children/child-details/child-details.component.ts

see issue: #302 
An error occured because of the wrong usage of the `ChildWithRelation` class. The class was saved to the database which is not what the class is ment for. This was changed to only save the `Child`-Object withing the `ChildWithRelation` object.

Fix saving of children

---

package.json
src/app/children/aser/aser.ts
src/app/entity/database-field.decorator.ts

Added the `reflect-metadata` API to get decorators the ability to retrieve type info of the decorated properties.

Reflect metadata

---

src/app/ui/ui/ui.component.html

Hi!
We spoke at #DigitaleNachtKA, and I didn't find any issue matching the "escape closes navigation" problem. Besides having 500MB of dependencies this might be the first repo I ever checked out and it worked out of the box after following the README.md. Thumbs up for that!

DIsable closing the menu on ESC

---

src/app/children/attendance/add-day-attendance/add-day-attendance.component.html

Add a `Back` button to the final view of the attendance-addition form

---

src/app/ui/ui/ui.component.css
src/app/ui/ui/ui.component.html

see issue: #252 
By wrapping the contents of the `<mat-sidenav-content>` element into a div, we now have a scrollable `<mat-sidenav-content>` whose contents can be padded correctly:
```diff
- <mat-sidenav-content class="sidenav-content">
+ <mat-sidenav-content>
+   <div class="sidenav-content">
<router-outlet *ngIf="isLoggedIn()"></router-outlet>
<app-login *ngIf="!isLoggedIn()"></app-login>
+   </div>
</mat-sidenav-content>
```
I hope this changes are not too hacky.

Change html to not overlap bottom screen

---

src/app/children/notes/notes-manager/notes-manager.component.ts

When adding a new Note, it appears in the list of notes immediately
after saving.
see issue: #328

Show recently added note after creation

---

package.json

It doesn't have a sourceRoot specified and `ng lint` doesn't support
multiple projects in a single command, so the removal should be fine for
now.
Fixes #380

Don't lint `ndb-core-e2e`

---

src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.html
src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.scss
src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.spec.ts
src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.ts
src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call-record.ts
src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.html
src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.scss
src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.spec.ts
src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts
src/app/child-dev-project/attendance/model/attendance-day.spec.ts
src/app/child-dev-project/attendance/model/attendance-day.ts
src/app/child-dev-project/attendance/model/attendance-month.spec.ts
src/app/child-dev-project/attendance/model/attendance-month.ts
src/app/child-dev-project/children/children.module.ts
src/app/child-dev-project/children/select-group-children/select-group-children.component.html
src/app/child-dev-project/children/select-group-children/select-group-children.component.scss
src/app/child-dev-project/children/select-group-children/select-group-children.component.spec.ts
src/app/child-dev-project/children/select-group-children/select-group-children.component.ts
src/app/core/entity/database-field.decorator.spec.ts
src/app/core/entity/schema-datatypes/datatype-array.ts
src/app/core/entity/schema-datatypes/datatype-date-only.ts
src/app/core/entity/schema-datatypes/datatype-schema-embed.ts
src/app/core/entity/schema/entity-schema-datatype.ts
src/app/core/entity/schema/entity-schema-field.ts
src/app/core/entity/schema/entity-schema.service.spec.ts
src/app/core/entity/schema/entity-schema.service.ts
src/app/core/ui-helper/filter-selection/filter-selection.ts

Fix problems with the attendance records. Especially an issue that the roll call (add day's attendance) feature wrongly jumped to a certain date instead of the selected date.
see issues: #390, #402

Bug fixes and improvements to AttendanceDay

---

src/app/child-dev-project/children/demo-data-generators/demo-child-school-relation-generator.service.ts
src/app/child-dev-project/schools/school-detail/school-detail.component.html

Issue #362 refers to the problem that when using the demo data, no children are displayed under the school detail component where the attending students are listed. 
This however, is not a bug in the component as @RichardNutt correctly  summarized [here](https://github.com/Aam-Digital/ndb-core/issues/362#issuecomment-566688561).
Instead, the demo data generator always created `ChildSchoolRelations` with the end date being set. 
Internally we say a student currently attends a school if there exists  a `ChildSchoolRelation` with this student and the school where the `end` attribute is `null`.
To create better demo data I changed the generator to make 80% of the students currently attending a school or in other words set the end date of the last `ChildSchoolRelation` to `null` with a 80% …

Generate children which currently attend a school

---

src/app/child-dev-project/children/child-block/child-block.component.html

see issue: #372 alt text for photos that can't be loaded

remove alternative text from image

---

src/app/child-dev-project/children/child-block/child-block.component.html
src/app/child-dev-project/children/child-details/child-details.component.css
src/app/child-dev-project/children/child-details/child-details.component.html
src/app/child-dev-project/children/child-details/child-details.component.ts
src/app/child-dev-project/children/child-photo-service/child-photo.service.spec.ts
src/app/child-dev-project/children/child-photo-service/child-photo.service.ts
src/app/child-dev-project/children/child-photo-service/datatype-load-child-photo.spec.ts
src/app/child-dev-project/children/child-photo-service/datatype-load-child-photo.ts
src/app/child-dev-project/children/children.service.spec.ts
src/app/child-dev-project/children/children.service.ts
src/app/child-dev-project/children/model/child.ts
src/app/core/entity/schema-datatypes/datatype-array.ts
src/app/core/entity/schema-datatypes/datatype-date-only.ts
src/app/core/entity/schema-datatypes/datatype-date.ts
src/app/core/entity/schema-datatypes/datatype-month.ts
src/app/core/entity/schema-datatypes/datatype-number.ts
src/app/core/entity/schema-datatypes/datatype-string.ts
src/app/core/entity/schema/entity-schema-datatype.ts
src/app/core/entity/schema/entity-schema.service.ts
src/app/core/ui/search/search.component.spec.ts
src/app/core/ui/search/search.component.ts

see issue: #366 
- please check the regex expression, it should allow only strings with at least one characters or number
- remeber: 
Search depends on pouchdb indices so this can only be debugged when setting useTemporaryDatabase to false in the config.json

optimized searchbar: only words, removed bug in parse rows

---

src/app/core/session/session-service/online-session.service.ts
src/app/core/session/session.service.provider.ts
src/app/core/ui/search/search.component.ts

add OnlineSessionService (currently online selectable by changing in code _core/session/session.service.provider.ts_ allowing to use the app through direct requests with the server database without local synced data.
This can be a useful mode for users to save time (no waiting till initial sync is complete) or when working on a device that the user is not regularly using (e.g. a public computer) where data should not be saved locally for security reasons also.
The OnlineSessionService mode is not usable without an internet connection. Offline functionality is not available.
TODO for later: requires a configuration or UI option to select OnlineSession (issue #434)

Online Session

---

src/app/child-dev-project/notes/dashboard-widgets/no-recent-notes-dashboard/no-recent-notes-dashboard.component.ts

Fixed little bug in no-recent-notes-dashboard.component.ts:
pipe(take(1)) was missing before .toPromise()

Fixed bug in no-recent-notes-dashboard.component.ts

---

src/app/child-dev-project/notes/notes-manager/notes-manager.component.scss

style(notes-manager): add full width to notes table

---

src/app/core/ui/search/search.component.html
src/app/core/ui/search/search.component.scss
src/app/core/ui/search/search.component.spec.ts
src/app/core/ui/search/search.component.ts
src/app/core/ui/ui/ui.component.scss

fix(search): fix weird behaving in search bar

---

src/app/child-dev-project/aser/aser-component/aser.component.spec.ts
src/app/child-dev-project/aser/aser-component/aser.component.ts
src/app/child-dev-project/attendance/child-attendance/child-attendance.component.spec.ts
src/app/child-dev-project/attendance/child-attendance/child-attendance.component.ts
src/app/child-dev-project/children/child-details/child-details.component.html
src/app/child-dev-project/children/child-details/child-details.component.ts
src/app/child-dev-project/children/child-details/dropout-form/dropout-form.component.html
src/app/child-dev-project/children/child-details/dropout-form/dropout-form.component.scss
src/app/child-dev-project/children/child-details/dropout-form/dropout-form.component.spec.ts
src/app/child-dev-project/children/child-details/dropout-form/dropout-form.component.ts
src/app/child-dev-project/children/child-details/grouped-child-attendance/grouped-child-attendance.component.html
src/app/child-dev-project/children/child-details/grouped-child-attendance/grouped-child-attendance.component.spec.ts
src/app/child-dev-project/children/child-details/grouped-child-attendance/grouped-child-attendance.component.ts
src/app/child-dev-project/children/child-details/health-form/health-form.component.html
src/app/child-dev-project/children/child-details/health-form/health-form.component.scss
src/app/child-dev-project/children/child-details/health-form/health-form.component.spec.ts
src/app/child-dev-project/children/child-details/health-form/health-form.component.ts
src/app/child-dev-project/children/children.module.ts
src/app/child-dev-project/educational-material/educational-material-component/educational-material.component.spec.ts
src/app/child-dev-project/educational-material/educational-material-component/educational-material.component.ts
src/app/child-dev-project/health-checkup/health-checkup-component/health-checkup.component.spec.ts
src/app/child-dev-project/health-checkup/health-checkup-component/health-checkup.component.ts
src/app/child-dev-project/notes/notes-of-child/notes-of-child.component.html
src/app/child-dev-project/notes/notes-of-child/notes-of-child.component.spec.ts
src/app/child-dev-project/notes/notes-of-child/notes-of-child.component.ts
src/app/child-dev-project/previous-schools/previous-schools.component.html
src/app/child-dev-project/previous-schools/previous-schools.component.spec.ts
src/app/child-dev-project/previous-schools/previous-schools.component.ts

see issue: #500
Besides the basic information, all the other components in the child details section only get the child object as an input. This is a step towards the goal, that the components which will later be displayed on the child details screen should be customizable.
I also created two new components for the `health` and the `dropout` information. These components are able to alter the child object of the surrounding child details class. This means clicking the save button in either of these components, saves the whole child entity and not just the `health` and `dropout` fields. 
- Additional save buttons for the `health` and `dropout` seection
- The form in `health` and `dropout` is always editable but only saved once the save button is pressed
- All used components in the child …

Child Details Subcomponents

---

src/app/child-dev-project/attendance/model/attendance-month.ts
src/app/core/entity/schema-datatypes/datatype-array.ts
src/app/core/entity/schema-datatypes/datatype-map.spec.ts
src/app/core/entity/schema-datatypes/datatype-map.ts
src/app/core/entity/schema/entity-schema-field.ts
src/app/core/entity/schema/entity-schema.service.spec.ts
src/app/core/entity/schema/entity-schema.service.ts

Schema datatype map

---

deploy/nginx/default.conf
docker/pipeline/Dockerfile

The proxy for Webdav is specified in the nginx config file `default.conf` and dependes on a environment variable.
This variable is now injected into the config file to fix the proxy.
- Webdav url injection

Fix Webdav proxy

---

.github/workflows/master-push.yml
build/karma-ci.conf.js

The GitHub workflow currently only uploaded a new Docker cache when a new tag was pushed. On changes that for example only affect the Dockerfile, no new tag is created by semantic release. In this case the Docker cache wont be updated but because the Dockerfile looks different than the one in the cache, the image have to be rebuilt every time. This change will now update the Docker cache on every build on the master as well as on tagged commits. The updating of the cache multiple times should not be a problem.
Due to the change of the folder structure of the `karma-ci.conf.js` the coverage exporter pointed to a wrong location which resulted in the coverage results not being found by the coverage exporter
- The Docker cache is updated on every build on the master branch
- Fixed the …

Improved Cache and Coverage Fix

---

src/app/core/view/dynamic-routing/router.service.spec.ts
src/app/core/view/dynamic-routing/router.service.ts

the app did not reflect config loaded from the database and instead always displayed the default config until now

fix(core): properly reload routing for config from database

---

src/app/app.component.ts
src/app/core/session/login/login.component.ts
src/app/core/ui/ui/ui.component.html
src/app/core/view/dynamic-routing/router.service.ts

see issue: #615 
- The config is applied at the initial sync 
- The current route is not lost when logging in/out
- The config is reloaded, once the sync status changes to `COMPLETED`
- After the config is loaded, a routing to the same location is started, to apply config that affects the first page that is already loaded

Fix Reloading Config

---

.github/workflows/master-push.yml
.github/workflows/pull-request-update.yml
build/Dockerfile

see issue: #610
Due to recent problems with the test stage, this image directly uploads the coverage results instead of copying them to the GitHub runner
--
- Docker image has additional flag for uploading the coverage report
- GitHub workflow for uploading test coverage was removed

Creating coverage report inside the docker image

---

.releaserc

Currently releases do not trigger the `new tag`  workflow due to [recent changes at GitHub](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/)
The default message is:
> "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
- Changed message created by Semantic Release

Remove skip ci message on release message by semantic release

---

src/app/child-dev-project/previous-schools/previous-schools.component.ts

- New `ChildSchoolRelations` are not initialized with null any more

Initializing new school relations correctly

---

src/app/core/admin/admin/admin.component.ts
src/app/core/admin/services/backup.service.ts

When importing a backup file where documents have the `_rev` field, CouchDB thinks the document is updated rather than created and throws document conflicts. Because the document should be overwritten anyways, the `_rev` field is now removed before saving the document to the database.
--
- Removing the `_rev` field of documents before saving it to database

Fix importing backup files

---

.github/workflows/master-push.yml

With this change, the `gh-pages` branch will only hold the latest commit and therefore drastically reduce the branch size

Orphan Commits for gh-pages

---

src/app/child-dev-project/children/children.service.spec.ts
src/app/child-dev-project/children/children.service.ts

A problem occurred (maybe just because of the time zone) where children were not correctly marked as attending a given school, when the starting date was same as today.
--
- Overworked function to calculate whether a child currently attends this school
- Added tests for the indices of the `ChildrenService`

Marking childSchoolRelations as active that start today

---

src/app/child-dev-project/attendance/attendance-calendar/attendance-calendar.component.html
src/app/child-dev-project/attendance/attendance-details/attendance-details.component.html
src/app/child-dev-project/attendance/attendance-details/attendance-details.component.ts

see issue: #729 
These texts have been updated to a more readable format:
None

Changed descriptions to a more suitable format

---

src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.ts
src/app/child-dev-project/attendance/attendance.service.spec.ts
src/app/child-dev-project/attendance/attendance.service.ts

The datepicker creates dates like `Mon Apr 05 2021 00:00:00 GMT+0200 (Central European Summer Time)`. The problem is, that currently `.getISOString()` is used to get the date in format `YYYY-MM-DD` but this will transform the datepicker date to `2021-04-04` (the day before) because of the timezone. This results in the wrong events being displayed in the record attendance section.
- Correct events are displayed in the `Recurring Activities`
- Using `moment` to format the date correctly

Event on wrong day bug

---

src/app/child-dev-project/notes/notes-manager/notes-manager.component.spec.ts
src/app/child-dev-project/notes/notes-manager/notes-manager.component.ts
src/app/core/entity-components/entity-list/entity-list.component.html

assigning the correct color is already in-built in the `Entity` class, which `Note` correctly overrides to add the custom logic that was duplicated here.

refactor: remove duplicate color assignment in notes-manager

---

src/app/child-dev-project/children/children.service.spec.ts
src/app/core/entity/entity-mapper.service.spec.ts

Recently Karma showed a deprecation note that `async` and `done()` should not be used in the same test and will not be supported in the future.
--
- changed tests where `async` and `done()` was used

Removed deprecated async done combination

---

src/app/child-dev-project/children/model/childSchoolRelation.spec.ts
src/app/core/entity/schema-datatypes/datatype-date-only.ts

When removing a existing date in the `Schools History` section, the application will throw an error and the change will not be saved. This is due to the datepicker setting a null value as the date and the transformation not checking if the value is null.
--
- Saving undefined if a null value is set to a date-only property

Fix null value is passed to date-only transformation

---

src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.html
src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.spec.ts
src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts

When a child is deleted but still part of a recurring activity or event, the roll call is in a inconsistent state.
This bug is now fixed.

Fix not existing children in roll call

---

src/app/child-dev-project/children/children-list/children-list.component.ts
src/app/child-dev-project/notes/notes-manager/notes-manager.component.ts
src/app/core/admin/admin/admin.component.ts
src/app/core/config/config-fix.ts
src/app/core/config/config.service.spec.ts
src/app/core/config/config.service.ts

The prebuilt filters directly work on the config and currently this changes are also exported when downloading the config. This has some bad sideeffects when using this config again. Instead the exported config is now directly taken from the database.

Prebuilt filter fix

---

src/app/core/config/config-fix.ts
src/app/features/reporting/reporting/report-row/report-row.component.html
src/app/features/reporting/reporting/reporting.component.ts

Report improvements

---

src/app/child-dev-project/children/child-photo-service/datatype-photo.spec.ts
src/app/child-dev-project/children/child-photo-service/datatype-photo.ts

Old photo format currently throws an error if the old value is `null`.
--

Datatype photo does not throw error

---

src/app/core/entity-components/entity-list/entity-list.stories.ts
src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.stories.ts
src/app/core/entity-components/entity-subrecord/list-paginator/list-paginator.component.html
src/app/core/entity-components/entity-subrecord/list-paginator/list-paginator.component.spec.ts
src/app/core/entity-components/entity-subrecord/list-paginator/list-paginator.component.ts

see issue: #868 
The paginator now works as follows:
- The all button is always enabled
- Enabling the all button will keep the all option enabled for all views on this table
- The other options (10, 20 50) are always available and call always be selected and will be maintained throughout the views of a table
- The all option is not automatically enabled once a page size is selected that is bigger than the amount of items.
--

Fix paginator all issue

---

src/app/child-dev-project/notes/note-details/note-details.component.html

see issue: #892
In the HTML of note-details.component.html instead of `(clicked)` we should rather use `(change)` and we should do this in the `mat-checkbox` and not the `mat-option` tag.

Fixing "Include inactive" not being set correctly

---

.github/workflows/tagged-commit.yml
.releaserc
build/Dockerfile
build/README.md
package.json
src/environments/environment.prod.ts
src/environments/environment.ts

switching to a new release process where stable releases are explicitly released onto the `official-release` branch

ci: new gitflow-like release process

---

src/app/core/database/pouch-database.ts

add logging information in case of document update conflicts to make sense of sentry errors

fix: better logging for document update conflicts in database

---

package-lock.json
package.json
src/app/core/session/session-service/remote-session.spec.ts
src/app/core/session/session-service/remote-session.ts
src/app/core/session/session-service/synced-session.service.spec.ts
src/app/core/session/session-service/synced-session.service.ts
src/app/core/session/session.module.ts
src/app/core/session/session.service.provider.ts

Part of #765.
Removing dependency to `pouchdb-authentication` and preparing for a one-database-per-entity scenario.
--

Rework remote session

---

src/app/child-dev-project/attendance/activity-list/activity-list.component.spec.ts
src/app/child-dev-project/children/children-list/children-list.component.spec.ts
src/app/child-dev-project/notes/notes-manager/notes-manager.component.spec.ts
src/app/child-dev-project/schools/schools-list/schools-list.component.spec.ts
src/app/core/entity-components/entity-list/entity-list.component.ts
src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.spec.ts
src/app/core/entity-components/entity-utils/entity-select/entity-select.component.spec.ts

See issue #896
**Backend changes / Fix**
When the filters are initialized, the activated route is being used to initialize any filter selections.
Additionally, the (filtered) data is only shown after the filter are properly initialized

Fix: Filter selections are considered when reloading the page

---

src/app/child-dev-project/children/children.service.ts
src/app/child-dev-project/educational-material/educational-material-component/educational-material.component.html
src/app/child-dev-project/educational-material/educational-material-component/educational-material.component.spec.ts
src/app/child-dev-project/educational-material/educational-material-component/educational-material.component.ts
src/app/child-dev-project/educational-material/model/educational-material.ts
src/app/child-dev-project/health-checkup/health-checkup-component/health-checkup.component.spec.ts
src/app/core/configurable-enum/edit-configurable-enum/edit-configurable-enum.component.html

see issue: #972
To solve this issue, `materialType` and `materialAmount` are required and `materialAmount` defaults to `1`. In my opinion, there is no point in storing a record with either no type or amount.
Additionally, this PR includes some changes in test-coverage, documentation and code-quality

Empty entries 972

---

src/manifest.json

There was a mismatch between the scope of the service worker and the scope/start url of the manifest file which resulted in some browsers not correctly detecting a matching service worker. This might also help with the problem that sometimes updates are not detected correctly on mobile devices.
Now the page is built in a way that a pwa can be installed for each locale (https://demo.aam-digital.com/en-US/) instead of having one pwa for the whole domain (https://demo.aam-digital.com)

Fix service worker problems

---

src/app/features/reporting/reporting/reporting.component.ts

Report Component no longer shows an error when config is undefined

---

src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.html
src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.ts
src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.spec.ts
src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts
src/app/core/entity/mock-entity-mapper-service.ts
src/app/core/session/mock-session.module.ts
src/app/utils/utils.spec.ts
src/app/utils/utils.ts

on request of one of our clients, this PR adds the option to configure a property by which participants are ordered when shown one after another in the "record attendance" / "roll call" workflow.
also, fixes #931

Sort roll call participants

---

src/app/core/export/export-service/export.service.ts

fix problem with deleted children in exports

---

src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.html
src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.scss
src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.ts
src/locale/messages.de.xlf
src/locale/messages.fr.xlf
src/locale/messages.xlf

Fix: Record Attendance without a date can no longer be edited

---

src/app/core/export/export-service/export.service.spec.ts
src/app/core/export/export-service/export.service.ts

fix: improve performance of download button

---

src/app/core/navigation/navigation/navigation.component.spec.ts
src/app/core/navigation/navigation/navigation.component.ts

fix: menu highlighting when no "/" route is set

---

doc/compodoc_sources/concepts/configuration.md
src/app/core/configurable-enum/configurable-enum-datatype/configurable-enum-datatype.spec.ts
src/app/core/configurable-enum/configurable-enum-datatype/configurable-enum-datatype.ts
src/app/core/configurable-enum/edit-configurable-enum/edit-configurable-enum.component.html
src/app/core/configurable-enum/edit-configurable-enum/edit-configurable-enum.component.ts
src/app/core/entity-components/entity-form/entity-form/entity-form.component.ts
src/app/core/entity-components/entity-form/entity-form/entity-form.stories.ts
src/app/core/entity/schema/entity-schema.service.spec.ts
src/app/core/entity/schema/entity-schema.service.ts
src/app/core/latest-changes/update-manager.service.ts

It's now possible to have configurable enums where multiple values can be selected.
This is according to angular materials [multi-select](https://material.angular.io/components/select/overview#multiple-selection) feature for the select component.

feat: multi select configurable enum

---

src/app/core/database/pouch-database.spec.ts
src/app/core/database/pouch-database.ts

Digging deeper into the problem already mentioned in #1178 it turns out that PouchDB exceptions have a `toString()` method which does only includes **some** parts of the exception object. 
By using a own object rather than the PouchDB one this has been changed so **all** properties are logged.
--

Custom Exception 

---

src/app/app.component.ts
src/app/child-dev-project/notes/note-attendance-block/note-attendance-count-block.component.ts
src/app/core/database/pouch-database.ts
src/app/core/demo-data/demo-data-initializer.service.ts
src/app/core/entity-components/entity-details/form/form.component.ts
src/app/core/entity-components/entity-form/entity-form.service.ts
src/app/core/entity-components/entity-form/entity-form/entity-form.component.ts
src/app/core/entity-components/entity-utils/view-components/readonly-function/entity-function.pipe.ts
src/app/core/export/download-service/download.service.ts
src/app/core/permissions/ability/entity-ability.ts
src/app/core/permissions/permission-enforcer/permission-enforcer.service.ts
src/app/core/permissions/permission-guard/user-role.guard.ts
src/app/core/webdav/webdav-wrapper.service.ts
src/app/features/data-import/data-import.service.ts

Compodoc does only correctly assign a comment to a class if it comes **before** the decorators (e.g. `@Injectable`).
Otherwise the comment is not shown for a given class in [our documentation](https://aam-digital.github.io/ndb-core/documentation/index.html).
-

doc: fixed docs to get correctly displayed by compodoc

---

doc/compodoc_sources/how-to-guides/dialogs-notifications.md
src/app/child-dev-project/attendance/add-day-attendance/add-day-attendance.component.ts
src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.spec.ts
src/app/conflict-resolution/compare-rev/compare-rev.component.spec.ts
src/app/conflict-resolution/compare-rev/compare-rev.component.ts
src/app/core/admin/admin/admin.component.spec.ts
src/app/core/admin/admin/admin.component.ts
src/app/core/confirmation-dialog/confirmation-dialog.service.spec.ts
src/app/core/confirmation-dialog/confirmation-dialog.service.ts
src/app/core/entity/entity-remove.service.spec.ts
src/app/core/entity/entity-remove.service.ts
src/app/core/form-dialog/form-dialog.service.spec.ts
src/app/core/form-dialog/form-dialog.service.ts
src/app/features/data-import/data-import.service.spec.ts
src/app/features/data-import/data-import.service.ts

Refactor open dialog

---

src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.stories.ts
src/app/core/entity-components/entity-utils/dynamic-form-components/edit-single-entity/edit-single-entity.component.html
src/app/core/entity-components/entity-utils/dynamic-form-components/edit-single-entity/edit-single-entity.component.ts

Currently there is a bad UX when editing a single entity:
This is due to the label being linked to the wrong input element.
--

Edit entity label fix

---

src/app/child-dev-project/attendance/attendance.service.spec.ts
src/app/child-dev-project/attendance/attendance.service.ts

Since the permission changes, the indices are created too early and therefore a wrong config (the default config) was used to create the event index `by_date` which resulted in a wrong behavior in the roll call setup.

removed interaction types from event index

---

src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-week-dashboard.component.html
src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-week-dashboard.component.scss
src/app/child-dev-project/children/dashboard-widgets/children-count-dashboard/children-count-dashboard.component.html
src/app/child-dev-project/children/dashboard-widgets/children-count-dashboard/children-count-dashboard.component.ts
src/app/child-dev-project/notes/dashboard-widgets/notes-dashboard/notes-dashboard.component.html
src/app/child-dev-project/notes/dashboard-widgets/notes-dashboard/notes-dashboard.component.scss
src/app/core/dashboard/dashboard-widget-base.scss
src/app/core/dashboard/dashboard-widget/dashboard-widget.component.html
src/app/core/dashboard/dashboard-widget/dashboard-widget.component.scss
src/app/core/dashboard/dashboard-widget/dashboard-widget.component.ts
src/locale/messages.de.xlf
src/locale/messages.fr.xlf
src/locale/messages.xlf

In some dashboard widgets, the `loading...` had no translation or was not even there at all.

Dashboard translation fix

---

src/app/child-dev-project/notes/dashboard-widgets/notes-dashboard/notes-dashboard.component.ts

fix: recent notes are sorted ascending

---

src/app/core/entity-components/entity-form/dynamic-form-validators/dynamic-validators.service.ts
src/locale/messages.de.xlf
src/locale/messages.fr.xlf
src/locale/messages.xlf

If not description for a validation error can be found, an error is thrown. This can result in the app being broken. 
Instead, a default error message "invalid input" is shown and a error is sent to the logging service which can then be inspected in Sentry.
--

validator is not throwing error if no validation message could be found

---

build/default.conf
build/merge-service-workers.js

Currently our offline functionality still has some limits. To reproduce:
1. Clear browser cache (at least for demo.aam-digital.com)
2. Visit https://demo.aam-digital.com/en-US/
3. Turn off internet
4. Reload page -> should work
5. Visit https://demo.aam-digital.com/
6. Does **not** work (not even `loading...` is shown)
This is because the root `index.html` (e.g. `https://demo.aam-digital.com/index.html`) is not actively cached by the service worker. 
This PR changes this and adds correct handling of requests to root without locale.
Try the same with https://test-deployment-pr-1266.herokuapp.com/en-US/ and https://test-deployment-pr-1266.herokuapp.com/ and it should work.
--

fix: index.html in root is correctly cached

---

.github/workflows/pre-release-cleanup.yml

closes #1138
I tested the referenced Github Action (https://github.com/dev-drprasad/delete-older-releases), running it locally to manually clean up pre-releases a few times. That worked seamlessly.

ci(*): remove pre-releases when publishing new official release

---

.github/workflows/pre-release-cleanup.yml
src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.spec.ts
src/app/child-dev-project/attendance/attendance.service.spec.ts
src/app/child-dev-project/attendance/attendance.service.ts
src/app/child-dev-project/children/children.service.spec.ts
src/app/child-dev-project/children/children.service.ts
src/app/child-dev-project/children/model/childSchoolRelation.ts
src/app/child-dev-project/children/previous-schools/previous-schools.component.spec.ts
src/app/child-dev-project/children/previous-schools/previous-schools.component.ts
src/app/child-dev-project/schools/children-overview/children-overview.component.spec.ts
src/app/child-dev-project/schools/children-overview/children-overview.component.ts
src/app/core/entity-components/entity-details/entity-details.component.spec.ts
src/app/features/historical-data/historical-data.service.ts

Currently the view that is used to load the currently active students on the school details page is bugged. It uses the current time to create the view which results in different students being displayed depending on the time at which the view was created.
This has been changed to use a in-memory filtering with the current date instead.

fix(*): Student overview correctly shows assigned students

---

doc/compodoc_sources/concepts/permissions.md

doc(permissions): Updated permission change instructions

---

src/app/core/permissions/permission-enforcer/permission-enforcer.service.spec.ts
src/app/core/permissions/permission-enforcer/permission-enforcer.service.ts

In the initial sync the permission enforcer might use the entity mapper before the config service has been set up. This is prevented by waiting for the config to be ready.

Permission enforcer fix

---

src/app/core/analytics/analytics.service.spec.ts
src/app/core/analytics/analytics.service.ts

Prevent matomo error messages in current master

fix(): prevent initialization errors of matomo

---

src/app/core/permissions/permission-enforcer/permission-enforcer.service.spec.ts
src/app/core/permissions/permission-enforcer/permission-enforcer.service.ts
src/app/utils/test-utils/generic-matchers.spec.ts

Permission enforcer currently doesnt work if a rule for `org.couchdb.user` is defined.
--

Fix permission enforcer

---

src/app/core/session/session-service/local-session.spec.ts
src/app/core/session/session-service/local-session.ts

fix: error with deprecated db name

---

src/app/core/entity-components/entity-details/entity-details.component.spec.ts
src/app/core/entity-components/entity-details/entity-details.component.ts

Currently, the loading indicator keeps spinning while creating a new entity in `EntityDetailsComponent`

fix: loading indicator is not shown when creating a new entity

---

src/app/core/database/pouch-database.ts

Sentry has a problem if a non-error object is thrown.
This should be solved by extending the `Error` class.

refactor: using Error subclass otherwise sentry reports this as an error

---

src/app/core/entity-components/entity-utils/entity-select/entity-select.component.html
src/app/core/entity-components/entity-utils/entity-select/entity-select.component.scss

Due to PR #1290, the position of the displayed entity is misaligned with the remove button. This PR fixes this by giving the entity-select a `display` of `inline-block`

Quick fix: Align the entity correct in the entity select component

---

src/app/core/view/dynamic-routing/not-found/not-found.component.spec.ts
src/app/core/view/dynamic-routing/not-found/not-found.component.ts

This should allow us to detect, if the configuration for a instance is missing some things (e.g. the support page)
--

fix: added logging for not-found component

---

src/app/child-dev-project/attendance/attendance.service.spec.ts
src/app/core/entity/schema-datatypes/datatype-map.spec.ts
src/app/core/entity/schema/entity-schema.service.spec.ts
src/app/utils/test-utils/generic-matchers.spec.ts

Some date tests are failing locally due to the problem with the timezone and date parsing, see #1355

test: fix problems with date tests

---

src/app/core/entity/schema-datatypes/datatype-date-only.spec.ts
src/app/core/entity/schema-datatypes/datatype-date-only.ts

After the recent fix for the `date-only` datatype a few errors popped up because some older users had dates in a different format stored. To still support these, a fallback is added to the date parsing.

fix(*): legacy date values are correctly parsed

---

src/app/core/entity-components/entity-list/entity-list.component.ts

Tables like the `ChildrenList` or the `NoteDetails` currently don't automatically switch to the mobile view because of a wrong ordering of events.
--

fix: tables adjust to mobile view

---

src/app/child-dev-project/schools/activities-overview/activities-overview.component.html
src/app/child-dev-project/schools/activities-overview/activities-overview.component.spec.ts
src/app/child-dev-project/schools/activities-overview/activities-overview.component.ts
src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.ts
src/app/core/entity-components/entity-subrecord/row-details/row-details.component.html
src/app/core/entity-components/entity-subrecord/row-details/row-details.component.spec.ts
src/app/core/entity-components/entity-subrecord/row-details/row-details.component.ts

Currently the row details component evaluates `update` permissions on the input entity. When clicking the `+` button on a table a new entity is created which can result in the popup being in disabled mode (e.g. a entity needs to have a certain value for the user to have `update` permissions). 
This is fixed by detecting, whether the entity is currently being created or updated.
Also, I discovered a small but in the `ActivitiesOverviewComponent`:
1. Create a new activity in the component
2. Edit this activity
3. The activity disappears from the table
This happens because the newly created entity is not present in the `records` array of the `ActivitiesOverviewComponent`.
--

fix: permissions are correctly applied in popup form

---

build/default.conf

When updating an instance to the new master, the first login results in a broken state because `/en-US/assets/config.json` does not exist anymore. This can be solved by forwarding the relative asset requests to the single assets folder.

assets request still work with a locale in the path

---

src/app/core/session/auth/keycloak/keycloak-auth.service.spec.ts
src/app/core/session/auth/keycloak/keycloak-auth.service.ts
src/app/core/session/session-service/local-session.spec.ts
src/app/core/session/session-service/local-session.ts
src/assets/keycloak.json

Small smaller fixes that came up during production like testing
--

Keycloak improvements

---

src/app/core/entity-components/entity-utils/entity-select/entity-select.component.spec.ts
src/app/core/entity-components/entity-utils/entity-select/entity-select.component.ts

Currently, the entity select autocomplete does not working when for example working with firstname - lastname instead of just name. This is fixed by using the default `toString()` function which can be configured through the `toStringAttributes`.

fix: entity select respects toStringAttributes

---

src/app/child-dev-project/notes/model/note.ts
src/app/child-dev-project/notes/note-details/note-details.component.html
src/app/child-dev-project/notes/note-details/note-details.component.ts
src/assets/locale/messages.de.xlf
src/assets/locale/messages.fr.xlf
src/assets/locale/messages.xlf

Currently, all the labels in the note details component are hard coded. To make this more in-line with the other labels that are used throughout the app the component now uses the (configurable) labels of the respective properties. This means the labels are the same everywhere in the app.

fix: labels in note details can be configured

---

src/app/child-dev-project/children/children.service.spec.ts
src/app/child-dev-project/children/children.service.ts
src/app/child-dev-project/notes/notes-of-child/notes-of-child.component.spec.ts
src/app/child-dev-project/notes/notes-of-child/notes-of-child.component.ts

see #1423 
The current `NotesOfChild` component only allows to show notes that are linked to a child.
This component has been made more abstract to also support notes of a school or notes of an author.
Currently the component is still called `NotesOfChild`. This name should be changed in the future to something like `RelatedNotes`. I have left it for now because I want to get this PR out fast and a change of the name would require a migration of existing configs.
--

Notes of schools and authors

---

src/app/child-dev-project/attendance/attendance-calendar/attendance-calendar.component.ts

When not selecting a date but receiving updates for the `EventNote` entity, a error is thrown because `this.selectedDate` is undefined in this case.

fix: error when no date is selected but data is received

---

src/app/child-dev-project/notes/dashboard-widgets/important-notes/important-notes.component.html
src/app/child-dev-project/notes/dashboard-widgets/important-notes/important-notes.component.scss

The left border didn't work as expected in Safari and looked buggy for the important notes dashboard component. This PR fixes this.

Fix: left border correctly works in Safari

---

src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-week-dashboard.component.spec.ts
src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-week-dashboard.component.ts

The attendance week dashboard does not use the offset at the moment

fixed typo for offset in attendance week dashboard

---

src/app/core/session/session-service/local-session.ts
src/app/core/session/session-service/synced-session.service.spec.ts

After we recently changed the usernames not to be case-sensitive, we forgot to adapt the `checkPassword` function. This function was still using the exact username. This has been fixed.
--

fix: passwords are correctly checked

---

src/app/core/session/auth/keycloak/account-page/account-page.component.html
src/app/core/session/auth/keycloak/account-page/account-page.component.spec.ts
src/app/core/session/auth/keycloak/account-page/account-page.component.ts
src/app/core/session/auth/keycloak/keycloak-auth.service.spec.ts
src/app/core/session/auth/keycloak/keycloak-auth.service.ts

When a user has changed its email but did not yet verify the email address, then the user is not able to log-in anymore.

fix: login attempt is correctly detected as unauthorised

---

src/app/core/entity-components/entity-utils/dynamic-form-components/edit-text-with-autocomplete/edit-text-with-autocomplete.component.html
src/app/core/entity-components/entity-utils/dynamic-form-components/edit-text-with-autocomplete/edit-text-with-autocomplete.component.scss
src/app/core/entity-components/entity-utils/dynamic-form-components/edit-text-with-autocomplete/edit-text-with-autocomplete.component.spec.ts
src/app/core/entity-components/entity-utils/dynamic-form-components/edit-text-with-autocomplete/edit-text-with-autocomplete.component.ts

add explanation to text-with-autocomplete field in the UI about how existing records are loaded or new records are created

fix(UI): add explanation to text-with-autocomplete field

---

src/app/core/entity/model/entity.ts
src/app/core/permissions/ability/ability.service.spec.ts
src/app/core/user/user.spec.ts
src/app/core/user/user.ts

When creating new user they currently get a UUID (like all other entities). The problem is we need the user's id to match the username of the Keycloak user. This is important in order to assign users to entities and then later match them with actually logged in users.
This approach initially overwrites the entity id when the first time a username is saved but afterwards does not allow to change the username anymore. This way we ensure that user entities can be matched with the usernames.
--

fix: using initial username as id and preventing later edits

---

src/app/core/latest-changes/latest-changes.service.ts
src/app/core/session/auth/keycloak/auth-interceptor.service.ts
src/app/core/session/auth/keycloak/auth.interceptor.spec.ts
src/app/core/session/auth/keycloak/keycloak-auth.service.ts

Currently the GitHub API requests fail because we sent a Bearer token with the request which is not valid for GitHub. 
This change allows to disable the setting of the Bearer token for special requests.

fix: GitHub API can be used again

---

src/app/core/user/user.spec.ts
src/app/core/user/user.ts

fix: users can be edited again

---

src/app/core/entity-components/entity-details/entity-details.component.html

add padding to entity details tabs again that went missing with previous ui fix

fix(ui): add padding to entity details tabs again

---

src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.html
src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.scss

When the create button in entity subrecord is disbled, it still looks like it can be used.
--

fix: styling of disabled create button

---

src/app/core/user/user-security/user-security.component.html
src/app/core/user/user-security/user-security.component.spec.ts
src/app/core/user/user-security/user-security.component.ts

see issue: #1626 
The current implementation is quite 'aggressive' in that it doesn't even allow a user to enter leading or trailing whitespaces. I think that this is fine since there is no valid email that starts or ends with a whitespace.

Notify on incorrect email, automatically trim whitespaces

---

e2e/integration/RecordingAttendanceOfChild.cy.ts
src/app/core/demo-data/demo-data-initializer.service.spec.ts
src/app/core/demo-data/demo-data-initializer.service.ts
src/app/core/permissions/ability/ability.service.ts

Because the database is initialised before the user is logged in, the ability service currently initialises the permissions too early. This has been changed, now the user is first logged in and then the database initialised and demo data published.
Also an error is fixed which happens if no rules are found for a user and no user is logged in. This can happen e.g. when there is not public rules.

fix(demo): demo data is only created after login

---

src/app/core/config/config-fix.ts
src/app/core/core-components.ts
src/app/core/entity-components/entity-details/related-entities/related-entities.component.html
src/app/core/entity-components/entity-details/related-entities/related-entities.component.spec.ts
src/app/core/entity-components/entity-details/related-entities/related-entities.component.ts
src/app/core/entity-components/entity-utils/entity-utils.ts
src/app/core/entity/database-indexing/database-indexing.service.ts
src/app/core/entity/entity-config.service.spec.ts
src/app/core/entity/entity-config.service.ts

Dynamic entities

---

src/app/core/ui/ui/ui.component.html
src/app/core/ui/ui/ui.component.scss

fix: buttons in sidenav take up full width

---

src/app/core/entity-components/entity-form/entity-form/entity-form.component.spec.ts
src/app/core/entity-components/entity-form/entity-form/entity-form.component.ts

one test still fails - I have no clue why the projectNumber is not coming in from the updatedEntity event but instead shows as undefined ...

fix: better automatic resolution of remote changes while editing forms

---

src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.spec.ts
src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.ts
src/app/core/config/config-fix.ts
src/app/core/entity/model/entity.ts
src/app/features/data-import/data-import/data-import.component.spec.ts

Hide inactive activities from roll call

---

src/app/core/export/query.service.spec.ts
src/app/core/export/query.service.ts

fix: report dates in the future don't throw errors

---

src/app/core/entity-components/entity-select/entity-select/entity-select.component.html
src/app/core/entity-components/entity-select/entity-select/entity-select.component.ts

fix: edit entity array is correctly displayed as disabled

---

proxy.conf.json
src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.spec.ts
src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts
src/app/core/configurable-enum/configurable-enum-datatype/configurable-enum-datatype.spec.ts
src/app/core/configurable-enum/configurable-enum-testing.ts
src/app/core/configurable-enum/configurable-enum.module.ts
src/app/core/configurable-enum/configurable-enum.service.spec.ts
src/app/core/configurable-enum/configurable-enum.service.ts
src/app/core/configurable-enum/edit-configurable-enum/edit-configurable-enum.component.spec.ts
src/app/core/configurable-enum/enum-dropdown/enum-dropdown.component.spec.ts

see issue: #1694 
It seems like there was a problem because the enums were loaded too late.
--

fix: enum service loads enums immediately

---

src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.spec.ts
src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.ts
src/app/child-dev-project/attendance/attendance.service.spec.ts
src/app/child-dev-project/attendance/attendance.service.ts
src/app/child-dev-project/children/children.service.spec.ts
src/app/child-dev-project/children/children.service.ts

In our logic to load notes, we currently always also update the participants list with new people that joined the group. This is useful in the roll call setup where you might want to also record their attendance stats. In other places where we only report the attendance without the option to modify it, this is not very useful as it will just add empty information (e.g. reports, dashboard components). This functionality has now been split up into two functions, one just loading the notes and one where the new participants are also added.
Another problem that I discovered is that the active participants are added based on the active status of today, not for the actual day where e.g. the roll call is conducted. This means also participants that have a start date of today would then be …

fix: reports only show actual participants of events

---

src/app/core/session/auth/auth.interceptor.spec.ts
src/app/core/session/auth/auth.interceptor.ts
src/app/core/session/session-service/synced-session.service.spec.ts
src/app/core/session/session-service/synced-session.service.ts

Currently, the case where the password is changed remotely and the user logs in with the old password, does **not** result in the user being logged out. This has been fixed. The user is now correctly logged out and the old password does not work anymore to log-in offline.

fix: failed remote login correctly logs-out user

---

src/app/child-dev-project/children/children-list/children-list.component.spec.ts
src/app/child-dev-project/children/children-list/children-list.component.ts
src/app/child-dev-project/children/children.service.ts
src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.ts

Some issues came up in production, probably due to longer loading times of the data.

Production issues

---

e2e/integration/MarkingChildAsDropout.cy.ts
src/styles/resets/_mat-input.scss

On Safari and especially on iPhone, the disabled forms are a little transparent and not fully black.

fix: forms have better visibility on iPhone

---

src/app/child-dev-project/children/dashboard-widgets/entity-count-dashboard/entity-count-dashboard.component.html
src/app/child-dev-project/children/dashboard-widgets/entity-count-dashboard/entity-count-dashboard.component.ts
src/app/core/dashboard-shortcut-widget/dashboard-shortcut-widget/dashboard-shortcut-widget.component.html
src/app/core/dashboard-shortcut-widget/dashboard-shortcut-widget/dashboard-shortcut-widget.component.scss
src/app/core/dashboard-shortcut-widget/dashboard-shortcut-widget/dashboard-shortcut-widget.component.spec.ts
src/app/core/dashboard-shortcut-widget/dashboard-shortcut-widget/dashboard-shortcut-widget.component.ts
src/app/core/dashboard/dashboard-list-widget/dashboard-list-widget.component.html

fix: added pagination to shortcut widget

---

src/app/core/config/config.service.ts
src/app/core/entity-components/entity-subrecord/list-paginator/list-paginator.component.ts
src/app/core/permissions/ability/ability.service.ts

- Currently, a warning is logged if a user only has default rules. As this is often the expected behaviour, these warnings are turned off. Now a warning is only shown if a user has no rules at all.
- removed the warning for `EditSingleEntity` and `EditEntityArray` as this sometimes is also ok to be used
- removed warning if a user entity is not found. With the user management, it is not possible to create a user without a entity first besides the admin accounts. For the admin accounts this error is not necessary though. Therefore, I don't see this error to still be relevant.

Removed various unnecessary logs

---

src/app/core/export/query.service.spec.ts
src/app/core/export/query.service.ts

It's possible to make a row without actually defining a query on it (e.g. to group further queries) this however currently throws error.

fix: missing queries don't throw errors

---

src/app/features/matching-entities/matching-entities/matching-entities.component.spec.ts
src/app/features/matching-entities/matching-entities/matching-entities.component.ts

The config of the matching component is currently leaking state as modifications happen directly on the config object and are therefore affecting visits of the same site in one session.
This has been fixed by making a deep copy using `JSON.parse` and `JSON.stringify`.
Can be reproduced by 
1. go to `/matching`
2. Select both entities with a distance
3. Navigate away and back to `/matching`
4. See that the distance form before is still shown in the tables and when the entity is selected. Also the distance is not updated when selecting different entities.

fix: state leaks in matching component

---

src/app/core/entity-components/entity-details/form/form.component.html
src/app/core/entity-components/entity-subrecord/row-details/row-details.component.html
src/app/core/form-dialog/form-dialog-wrapper/form-dialog-wrapper.component.html
src/app/core/user/user-security/user-security.component.html
src/app/features/matching-entities/matching-entities/matching-entities.component.html
src/app/features/progress-dashboard-widget/edit-progress-dashboard/edit-progress-dashboard.component.html
src/app/features/todos/todo-details/todo-details.component.html

see issue: #1743 
These changes should generally highlight the action that is most likely to be used (saving) to make this more visible and also make the general styling of the save and cancel buttons more common across all screens.

Better buttons

---

e2e/integration/MarkingChildAsDropout.cy.ts
src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.spec.ts
src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.ts

fix: roll call setup shows all activities if none match the current user

---

src/app/core/entity-components/entity-subrecord/row-details/row-details.component.html
src/app/core/entity-components/entity-subrecord/row-details/row-details.component.spec.ts
src/app/core/entity-components/entity-subrecord/row-details/row-details.component.ts

fix: add button to navigate to details page if available

---

src/app/core/session/session-service/synced-session.service.spec.ts
src/app/core/session/session-service/synced-session.service.ts

Trying to solve the `Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.` which sometimes causes the sync to stop and some data not being synchronised. At the moment this can only be solved by calling the `/db/admin/clear_local/app` endpoint (which triggers a check of all revs at source and target).

Sync restart on errors

---

src/app/child-dev-project/children/model/child.ts

At one instance, the child's status property has been overwritten to be a multi select, which led to issues when the default value `""` was assigned in the child class.
--
--

fix: broken status when using multiple select

---

src/app/core/entity-components/entity-subrecord/entity-subrecord/entity-subrecord.component.ts

fix: months are sorted descending

---

src/app/core/entity/entity-mapper.service.spec.ts
src/app/core/entity/entity-mapper.service.ts
src/app/core/entity/mock-entity-mapper-service.ts
src/app/core/entity/model/entity.ts
src/app/core/entity/model/update-metadata.ts

feat(core): record metadata when entity is created and updated

---

src/app/child-dev-project/attendance/attendance.service.ts
src/app/child-dev-project/children/children.service.ts
src/app/child-dev-project/notes/dashboard-widgets/notes-dashboard/notes-dashboard.component.ts
src/app/child-dev-project/notes/model/note.ts
src/app/child-dev-project/notes/note-details/note-details.component.html
src/app/child-dev-project/notes/note-details/note-details.component.ts
src/app/core/configurable-enum/configure-enum-popup/configure-enum-popup.component.ts
src/app/core/entity-components/entity-select/display-entity/display-entity.component.spec.ts
src/app/core/entity-components/entity-select/display-entity/display-entity.component.ts
src/app/core/entity-components/entity-utils/entity-property-view/entity-property-view.component.ts

Smaller fixes

---

src/app/core/entity-components/entity-select/display-entity/display-entity.component.ts

Currently, when a single entity is supposed to be displayed but not set (undefined) then an error is logged.

fix: display entity component does not try to load undefined entities

---

src/app/core/entity-components/entity-select/edit-entity-array/edit-entity-array.component.html

Save button is disabled in note details if only an entity-array field is changed.

fix: editing entity array correctly marks a form as dirty

---

src/app/core/session/auth/auth.service.ts
src/app/core/session/auth/couchdb/couchdb-auth.service.ts
src/app/core/session/auth/keycloak/keycloak-auth.service.ts
src/app/core/session/session-service/remote-session.ts
src/app/core/session/session-service/synced-session.service.spec.ts
src/app/core/session/session-service/synced-session.service.ts
src/app/core/support/support/support.component.spec.ts
src/app/core/support/support/support.component.ts

Sync completions are not send to Sentry directly and instead just logged as a information in case other errors occur.
Errors are still send to sentry but hold information about the last successful authentication which should help to understand, why these errors occur. The last authentication timestamp has been improved to be updated whenever a new access token has been received (in the Keycloak case).

fix: improved logging for failed sync

---

src/app/core/session/auth/keycloak/password-reset/password-reset.component.html
src/app/core/session/auth/keycloak/password-reset/password-reset.component.ts
src/app/core/session/login/login.component.html

Currently the app automatically reloads when clicking the reset password button. 
-  ~Matomo is not yet working on the reset password button~ (we only initialise after login as it needs the config)

fix: reset password button does not reload app

---

src/app/core/common-components/template-tooltip/template-tooltip.component.ts
src/app/core/common-components/template-tooltip/template-tooltip.directive.ts
src/app/core/language/language-select/language-select.component.ts
src/app/core/latest-changes/app-version/app-version.component.ts
src/app/core/navigation/navigation/navigation.component.ts
src/app/core/pwa-install/pwa-install.component.ts
src/app/core/sync-status/sync-status/sync-status.component.ts
src/app/core/ui/primary-action/primary-action.component.ts
src/app/core/ui/search/search.component.ts
src/app/core/ui/ui/ui.component.ts
src/app/core/view/fa-dynamic-icon/fa-dynamic-icon.component.ts

see issue: #1586 
This PR uses two approaches to improve the performance of change detection.
One reason for a lot of (unnecessary) change detection cycles is the use of event listeners in child components. These events trigger change detection on all ancestor components (see [here](https://medium.com/angular-in-depth/deep-dive-into-the-onpush-change-detection-strategy-in-angular-fab5e4da1d69#4072)). E.g. when using `@HostListener("mouseover")` change detection for all ancestor components up to the `app-component` is triggered whenever the mouse moves over the element. This can be prevented by moving the subscription to the event outside of the `NgZone` and only enter the zone again if the UI should be manipulated. Unfortunately the `MatTooltip` and `MatSort` directive also have this …

Change detection improvements

---

src/app/core/entity-components/entity-form/entity-form/entity-form.component.spec.ts
src/app/core/entity-components/entity-form/entity-form/entity-form.component.ts

Creating a new note (without changing the date) currently triggers the save changes popup.

fix: date-only field does not trigger confirm changes popup

---

.github/workflows/master-push.yml

The visual regression tests are not executed on the master branch yet and therefore no comparison can be made.

ci: master push triggers percy

---

src/app/core/support/support/support.component.spec.ts
src/app/core/support/support/support.component.ts

The report screen reloads the app but after that the user is stuck in the report screen without a way to navigate to the login page.
This change will forward the user to the normal login screen after the app has been reset.

fix: app reset does not get stuck on support screen

---

.github/workflows/semantic-release.yml
.releaserc

This is a PR to update the semantic-release-replace-plugin to the [new package](https://www.npmjs.com/package/semantic-release-replace-plugin) from the [deprecated version](https://www.npmjs.com/package/@google/semantic-release-replace-plugin).

chore: update deprecated plugin to new package

---

src/app/child-dev-project/notes/notes-related-to-entity/notes-related-to-entity.component.spec.ts
src/app/child-dev-project/notes/notes-related-to-entity/notes-related-to-entity.component.ts
src/app/utils/utils.ts

by checking any referenced entities in properties of the current entity for those that match the entity types allowed in Note.relatedEntities schema
-> a step towards more generalized ChildSchoolRelation

feat(core): link any permitted relatedEntities to newly generated Note

---

src/app/features/location/location.datatype.spec.ts
src/app/features/location/location.datatype.ts

closes #1957 
Implemented basic use case without a configuration UI or user feedback. Looking into #1844 to enable any address information to be imported without data loss.

feat(import): import address by lookup of location data

---

src/app/child-dev-project/children/model/child.ts
src/app/features/file/edit-photo/edit-photo.component.html
src/app/features/file/edit-photo/edit-photo.component.scss
src/app/features/file/edit-photo/edit-photo.component.ts

The photo field until now did not display any form-field label. This is becoming an issue as the field is more widely used and there are forms with multiple photo fields.
- photo field has a label like any other field now
- I failed to keep the image centered within form-field, but the left bound layout also looks fairly clean and consistent now in my opinion.

fix(forms): display label for photo fields

---

src/styles/mdc_overwrites/mdc_overwrites.scss

The date range picker does not highlight the selected range anymore.

fix: range background color in date picker

---

src/app/core/filter/filter/filter.component.spec.ts
src/app/core/filter/filters/filters.spec.ts
src/app/core/filter/filters/filters.ts

so that entities for which the user has not touched a checkbox field (leaving it unchecked) are correctly included
:warning: mark commit for @codo-mentoring

fix(filters): "false" option of boolean filters includes undefined

---

src/app/core/entity-details/related-time-period-entities/time-period.spec.ts
src/app/core/entity-details/related-time-period-entities/time-period.ts

allow date ranges where start date is in future and no end date is set
:warning: mark commit for @codo-mentoring

fix(*): correctly allow date ranges where start date is in future

---

src/app/core/common-components/entity-subrecord/entity-subrecord/entity-subrecord.component.html
src/app/core/common-components/entity-subrecord/entity-subrecord/entity-subrecord.component.ts
src/app/core/entity-details/entity-details/entity-details.component.html
src/app/core/entity-details/entity-details/entity-details.component.spec.ts
src/app/core/entity-details/entity-details/entity-details.component.ts
src/app/core/entity/entity-remove.service.spec.ts
src/app/core/entity/entity-remove.service.ts
src/app/core/form-dialog/dialog-buttons/dialog-buttons.component.spec.ts
src/app/core/form-dialog/dialog-buttons/dialog-buttons.component.ts

in preparation of implementing anonymization (#1674)
---------
This functionality has been developed for the project “codo”. codo is developed under the projects “Landungsbrücken – Patenschaften in Hamburg stärken” and “openTransfer Patenschaften”. It is funded through the program “Menschen stärken Menschen” by the German Federal Ministry of Family Affairs, Senior Citizens, Women and Youth. More information at https://github.com/codo-mentoring
“Landungsbrücken – Patenschaften in Hamburg stärken” is a project of BürgerStiftung Hamburg in cooperation with the Mentor.Ring Hamburg. With a mix of networking opportunities, capacity building and financial support the project strengthens Hamburg’s scene of mentoring projects since its founding in 2016.
The “Stiftung Bürgermut” foundation since …

refactor(core): simplify entity-remove service

---

src/app/child-dev-project/children/educational-material/educational-material-component/educational-material.component.html
src/app/child-dev-project/children/educational-material/educational-material-component/educational-material.component.spec.ts
src/app/child-dev-project/children/educational-material/educational-material-component/educational-material.component.ts
src/app/core/config/config-fix.ts

Extend educational material summary

---

src/app/core/common-components/confirmation-dialog/confirmation-dialog.service.ts
src/app/core/common-components/edit-text-with-autocomplete/edit-text-with-autocomplete.component.spec.ts
src/app/core/common-components/entity-form/entity-form/entity-form.component.spec.ts
src/app/core/common-components/entity-form/entity-form/entity-form.component.ts

related to PR #2012 
:warning: mark as @codo-mentoring 
We have apparently not properly handled some edge cases, when applying remote changes to a form. This has become an issue when anonymizing records.

fix(forms): correctly apply remote changes to form if removing a property

---

.github/workflows/pull-request-update.yml
build/Dockerfile
src/app/child-dev-project/attendance/attendance.service.spec.ts
src/app/child-dev-project/attendance/attendance.service.ts
src/app/child-dev-project/children/children.service.spec.ts
src/app/child-dev-project/children/children.service.ts
src/app/core/basic-datatypes/date/date-range-filter/date-range-filter-panel/date-range-filter-panel.component.spec.ts
src/app/core/basic-datatypes/date/date-range-filter/date-range-filter.component.spec.ts
src/app/core/basic-datatypes/map/map.datatype.spec.ts
src/app/core/basic-datatypes/schema-embed/schema-embed.datatype.spec.ts
src/app/core/export/download-service/download.service.spec.ts
src/app/core/filter/filter.service.spec.ts
src/app/core/filter/filter.service.ts
src/app/core/filter/filters/filters.ts

The events/notes on a specific date did not work with a timezone `UTC -0500` (negative offset) because `new Date("2022-01-01")` is then interpreted as `Fri Dec 31 2021 19:00:00 GMT-0500 (Eastern Standard Time)`. 
The moment adapter handles this better or `new Date(2022, 0, 1)` also works.

Timezone index fix

---

src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-week-dashboard.component.spec.ts
src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-week-dashboard.component.ts
src/app/core/common-components/entity-form/entity-form.service.spec.ts

Somehow I am too stupid to get this right. This is the second try after initially tests had failed when running on Sundays ...
Please double-check, @TheSlimvReal

fix(dashboard): attendance weeks only start from Monday correctly

---

src/app/child-dev-project/notes/note-details/note-details.component.spec.ts
src/app/utils/database-testing.module.ts

Some tests in the query service sometimes failed.
This is because the property `religion` is only defined in the config and the config attributes were not applied in the test environment. So in some cases the entity was not set up properly and the queries using this attribute failed.

Query test fix

---

src/app/core/permissions/permission-enforcer/permission-enforcer.service.ts
src/app/core/session/login/login.component.spec.ts
src/app/core/session/login/login.component.ts
src/app/core/session/session.module.ts

Currently it's not possible to visit the public forms without logging in. This is because I triggered the login process in a module which will always be executed. I moved this now to the login component, so other (public) components can be visited without logging in.

Login not required

---

src/app/core/entity/database-entity-decorator.spec.ts
src/app/core/entity/database-entity.decorator.ts
src/app/core/entity/database-field.decorator.ts

If currently only the `@DatabaseEntity` property is used without any property being decorated with `@DatabaseField`, then the schema object from the superclass is used. This results in new properties also being added to the superclass's schema.

fix: prevent usage of superclass schema

---

src/app/app.routing.ts
src/app/core/admin/admin.routing.ts
src/app/core/permissions/permission-guard/entity-permission.guard.spec.ts
src/app/core/permissions/permission-guard/entity-permission.guard.ts
src/app/core/ui/navigation/navigation/navigation.component.spec.ts
src/app/core/ui/navigation/navigation/navigation.component.ts

Guards fix

---

src/app/child-dev-project/schools/display-participants-count/display-participants-count.component.html
src/app/child-dev-project/schools/display-participants-count/display-participants-count.component.spec.ts
src/app/child-dev-project/schools/display-participants-count/display-participants-count.component.ts
src/app/child-dev-project/schools/schools-components.ts
src/app/core/config/config-fix.ts
src/app/core/entity/default-datatype/view.directive.ts
src/app/core/entity/model/entity.ts

feat(schools): school list show a column stating the total number of participants

---

src/app/core/common-components/entity-form/entity-form.service.spec.ts
src/app/core/common-components/entity-form/entity-form.service.ts
src/app/core/entity-details/form/form.component.spec.ts

fix: correctly reset special fields like username when cancelling forms

---

src/app/child-dev-project/attendance/activities-overview/activities-overview.component.ts
src/app/child-dev-project/attendance/activity-attendance-section/activity-attendance-section.component.html
src/app/child-dev-project/attendance/attendance-details/attendance-details.component.html
src/app/child-dev-project/notes/notes-related-to-entity/notes-related-to-entity.component.html
src/app/child-dev-project/notes/notes-related-to-entity/notes-related-to-entity.component.spec.ts
src/app/child-dev-project/notes/notes-related-to-entity/notes-related-to-entity.component.ts
src/app/core/common-components/entities-table/entities-table.component.html
src/app/core/common-components/entities-table/entities-table.component.spec.ts
src/app/core/common-components/entities-table/entities-table.component.ts
src/app/core/entity-details/related-entities/related-entities.component.ts
src/app/core/entity-list/entity-list/entity-list.component.html
src/app/features/matching-entities/matching-entities/matching-entities.component.html
src/app/features/todos/todos-related-to-entity/todos-related-to-entity.component.html
src/app/features/todos/todos-related-to-entity/todos-related-to-entity.component.ts

Closes #2188
Alternative to #2190
TODO

[Simon] fix: plus button in notes / tasks of child correctly opens popup again 

---

src/app/core/common-components/entity-form/entity-form/entity-form.component.spec.ts
src/app/core/common-components/entity-form/entity-form/entity-form.component.ts

fix: use create permissions when read public form fields

---

src/app/core/common-components/entities-table/entities-table.component.html
src/app/core/common-components/entities-table/entities-table.component.ts

When in selectable mode in an entity table, clicking the checkbox navigated to the details of that entity. This is fixed here.
It is also added here that clicking on a row in selectable mode has the same effect as clicking the checkbox.

Fixed bug of navigating to entity details even in selectable mode

---

src/app/core/common-components/entities-table/entities-table.component.spec.ts
src/app/core/common-components/entities-table/entities-table.component.ts
src/app/core/entity-details/related-entities/related-entities.component.html
src/app/core/entity-details/related-entities/related-entities.component.ts
src/app/core/entity-details/related-time-period-entities/related-time-period-entities.component.ts

fix: correctly opening creating new page when clicking "+" button

---

src/app/core/basic-datatypes/entity/display-entity/display-entity.component.html
src/app/core/basic-datatypes/entity/display-entity/display-entity.component.scss

closes #1762
this only fixes the behavior of the "entity-array" fields but through #2175 this will also soon apply to single-select "entity" fields.

fix: navigate to details upon click in "entity-select" form field

---

src/app/core/permissions/permission-guard/abstract-permission.guard.spec.ts
src/app/core/permissions/permission-guard/abstract-permission.guard.ts

has caused errors that show up in sentry:
> Invalid regular expression: /^**[/.*]*$/: Nothing to repeat

fix(core): generate valid regex in guard also for wildcard routes

---

src/app/core/entity-list/entity-list/entity-list.stories.ts
src/app/core/user/user.spec.ts
src/app/core/user/user.ts

remove code from User entity class that is not used anymore since we have separated user account logic from the business logic entities.

refactor: remove deprecated User fields and functionalities

---

src/app/core/admin/admin-entity/admin-entity.component.spec.ts
src/app/core/admin/admin-entity/admin-entity.component.ts
src/app/core/entity-details/entity-details/entity-details.component.html
src/app/core/entity-list/entity-list/entity-list.component.html

closes:  #2324
-  Added query parameters into the routes to entity details and list screen.
-  Create a function in the AdminEntityComponent to retrieve details from the query parameters.
-  Utilize the mode property to set the modes.
-  Empty the params when users coming from specific screen

 #2324/ Admin UI should accept queryParam to route to details or list editor view

---

src/app/core/common-components/entity-form/entity-form.service.spec.ts
src/app/core/common-components/entity-form/entity-form.service.ts
src/app/core/entity/entity-actions/entity-anonymize.service.spec.ts
src/app/core/entity/entity-actions/entity-anonymize.service.ts
src/app/core/entity/schema/entity-schema.service.spec.ts
src/app/core/entity/schema/entity-schema.service.ts

fix(forms): reset anonymized fields immediately

---

src/app/child-dev-project/attendance/add-day-attendance/roll-call-setup/roll-call-setup.component.ts
src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts
src/app/child-dev-project/attendance/attendance-calendar/attendance-calendar.component.ts
src/app/child-dev-project/attendance/attendance-details/attendance-details.component.ts
src/app/child-dev-project/notes/dashboard-widgets/important-notes-dashboard/important-notes-dashboard.component.ts
src/app/child-dev-project/notes/notes-related-to-entity/notes-related-to-entity.component.ts

after the view-architecture rework
(NotesRelatedToEntities in a details view and others did not show a popup anymore)

fix: correctly open note details popup everywhere

---

src/app/core/common-components/basic-autocomplete/basic-autocomplete.component.html
src/app/core/common-components/basic-autocomplete/basic-autocomplete.component.ts

fixes #2389
using Angular's built-in "virtual scrolling": https://material.angular.io/cdk/scrolling/overview
---
Tested by overwriting DemoModule generator: `DemoChildGenerator.provider({ count: 10000 }),`

fix: load entity selection fields much faster for large databases

---

src/app/core/database/sync.service.ts
src/app/features/file/couchdb-file.service.spec.ts
src/app/features/file/couchdb-file.service.ts
src/app/features/file/file.service.ts

fixes #2398
The replication-backend needs to load the entity (from the "app" db) for permission checks during the file upload (put on the "app-attachments" db). For newly created documents we need to ensure the sync (nowadays at scheduled intervals) is completed before the upload.

fix: ensure file upload works on newly created records

---

src/app/child-dev-project/notes/model/note.ts
src/app/child-dev-project/notes/notes-related-to-entity/notes-related-to-entity.component.spec.ts
src/app/child-dev-project/notes/notes-related-to-entity/notes-related-to-entity.component.ts

For some use cases we overwrite the `ChildSchoolRelation` schema to enabe n-to-m relationships, i.e. allowing `childId` and `schoolId` to be arrays. This can cause errors in the NoteDetails component currently

fix: fix errors when creating note on group relation record

---

src/app/core/entity/database-field.decorator.ts
src/app/features/reporting/report-config.ts
src/app/features/reporting/reporting/reporting.component.spec.ts
src/app/features/reporting/reporting/select-report/select-report.component.html
src/app/features/reporting/reporting/select-report/select-report.component.spec.ts
src/app/features/reporting/reporting/select-report/select-report.component.ts
src/app/features/reporting/sql-report/sql-report.service.spec.ts
src/app/features/reporting/sql-report/sql-report.service.ts

feat: support for sql reports without date range

---

src/app/core/entity-list/duplicate-records/duplicate-records.service.spec.ts
src/app/core/entity/entity-actions/entity-actions.service.spec.ts
src/app/core/entity/entity-actions/entity-actions.service.ts
src/app/core/entity/entity-actions/entity-delete.service.spec.ts
src/app/core/entity/entity-actions/entity-delete.service.ts
src/app/core/session/auth/keycloak/keycloak-auth.service.spec.ts
src/app/core/session/auth/keycloak/keycloak-auth.service.ts

closes: https://github.com/Aam-Digital/ndb-core/issues/1874

feat: delete keycloak user when deleting user entity

---

src/app/core/admin/admin-entity-details/admin-entity-field/admin-entity-field.stories.ts
src/app/core/common-components/basic-autocomplete/basic-autocomplete.component.html
src/app/core/common-components/basic-autocomplete/basic-autocomplete.component.spec.ts
src/app/core/common-components/basic-autocomplete/basic-autocomplete.component.ts

- avoid ExpressionChangedAfterItHasBeenCheckedError caused by use of `focused` in own template
- fix displaying of all options when reopening

fix: fix some glitches in the behavior of dropdown components

---

src/app/child-dev-project/notes/dashboard-widgets/important-notes-dashboard/important-notes-dashboard.component.html
src/app/child-dev-project/notes/dashboard-widgets/important-notes-dashboard/important-notes-dashboard.component.ts
src/app/core/config/config-fix.ts
src/app/features/dashboard-widgets/birthday-dashboard-widget/birthday-dashboard/birthday-dashboard.component.html
src/app/features/dashboard-widgets/birthday-dashboard-widget/birthday-dashboard/birthday-dashboard.component.ts
src/app/features/dashboard-widgets/entity-count-dashboard-widget/entity-count-dashboard/entity-count-dashboard.component.html
src/app/features/dashboard-widgets/entity-count-dashboard-widget/entity-count-dashboard/entity-count-dashboard.component.ts
src/app/features/dashboard-widgets/entity-count-dashboard-widget/entity-count-dashboard/entity-count-dashboard.stories.ts
src/app/features/dashboard-widgets/progress-dashboard-widget/progress-dashboard/progress-dashboard.component.html
src/app/features/dashboard-widgets/progress-dashboard-widget/progress-dashboard/progress-dashboard.component.ts
src/app/features/dashboard-widgets/shortcut-dashboard-widget/shortcut-dashboard/shortcut-dashboard.component.html
src/app/features/dashboard-widgets/shortcut-dashboard-widget/shortcut-dashboard/shortcut-dashboard.component.ts
src/app/features/todos/todos-dashboard/todos-dashboard.component.html
src/app/features/todos/todos-dashboard/todos-dashboard.component.ts

feat: add configurable subtitle and explanation inputs

---

src/app/core/filter/filters/filters.ts

prevent angular warnings for duplicate keys in options drop down.

fix: prevent duplicate keys in filter options

---

.github/workflows/pull-request-update-or-push-tag.yml

as this clutters the Error Monitoring platform and makes it confusing to use "Resolved in the next release"

ci: stop adding PR builds as releases in Sentry

---

src/app/features/notification/model/notification-event.ts
src/app/features/notification/notification.component.ts

[Feat]: Notification entry navigates to the relevant view 

---

src/app/features/notification/model/entity-notification-context.ts
src/app/features/notification/model/notification-event.ts
src/app/features/notification/notification.component.spec.ts
src/app/features/notification/notification.component.ts

closes: https://github.com/Aam-Digital/ndb-core/issues/2754

Update the Notification event to relevent view

---

src/app/core/basic-datatypes/entity/entity-block/entity-block.component.scss
src/app/core/common-components/entities-table/entities-table.component.spec.ts
src/app/core/common-components/entities-table/entities-table.component.ts
src/styles/globals/_utility-classes.scss

refactor: row click handling in EntitiesTableComponent

---

src/app/core/entity/edit-entity-type/edit-entity-type.component.html
src/app/core/entity/edit-entity-type/edit-entity-type.component.ts
src/app/features/template-export/template-export.entity.ts

fix: Add required validation for applicableForEntityTypes field

---

src/app/features/notification/model/notification-config.ts

see https://github.com/Aam-Digital/ndb-core/issues/2847
Make userId available on NotificationConfig entity because replication-backend cannot have a placeholder in combination with normal text (yet)
i.e.
possible:
```
{
"subject": "NotificationConfig",
"action": "manage",
"conditions": {
"userId": "${user.id}"
}
},
```
not supported in backend:
```
{
"subject": "NotificationConfig",
"action": "manage",
"conditions": {
"_id": "NotificationConfig:${user.id}"
}
},
```
related to https://github.com/Aam-Digital/replication-backend/pull/171

Notification userid

---

src/app/core/common-components/entities-table/entities-table.component.scss

The Entity Actions column (with buttons) should always be the least possible width

---

.github/workflows/pull-request-update-or-push-tag.yml

closes: #2952
Integrated new Github action service and took references from here [Docker’s GHA Cache Backend Docs](https://docs.docker.com/build/cache/backends/gha/)

GitHub Action cache needs to be migrated 

---

.github/workflows/on-master-push.yml
.github/workflows/pull-request-update-or-push-tag.yml
build/Dockerfile
e2e/tests/attendance-tests.spec.ts
e2e/tsconfig.json
eslint.config.mjs
package-lock.json
package.json

Lint and type-check e2e test code. I’ve created a separate tsconfig file for the e2e code so that we cna start with best practices like setting strict mode.
I also created a new `code-quality` step in the workflows and moved the lint step there from the test step. This means we can run the steps in parallel and get quicker feedback.
I opted to run `eslint` instead of `ng lint ndb-core` because the former is more flexible and faster.

feat: Lint and type-check e2e test code

---

build/karma-ci.conf.js
e2e/tests/attendance-tests.spec.ts
e2e/tests/dashboard-tests.spec.ts
e2e/tsconfig.json
karma.conf.js
package-lock.json
package.json
playwright.config.ts
src/app/child-dev-project/children/demo-data-generators/fixtures/religions.ts
src/app/child-dev-project/warning-level.ts
src/app/core/common-components/entities-table/value-accessor/value-accessor.ts
src/app/core/entity/default-datatype/default.datatype.ts

With #2995 we plan to import app code in the test runner. This PR prepares for that change.
* Remove CommonJS/Angular quirks from app code
* Align tsconfig between code bases
* Use [tsx](https://github.com/privatenumber/tsx) to support app’s tsconfig in test runner. We want the e2e test code run by Playwright to be transformed with TypeScripts [`experimentalDecorators`][1] option. Playwrights builtin
transformer [does not support][2] this option. Instead we disable the builtin transformer and use `tsx`.
[1]: https://www.typescriptlang.org/tsconfig/#experimentalDecorators
[2]: https://playwright.dev/docs/test-typescript#tsconfigjson

Make e2e test code and app code compatible

---

.github/workflows/_qa.yaml
src/app/core/user/user-security/user-security.stories.ts

I think it’s a good idea to type-check all app code separately. This surfaced on
type issue in one of the Storybook stories.

refactor: Type-check app code on CI

---

src/app/child-dev-project/notes/note-details/note-details.component.ts
src/app/core/common-components/entities-table/entities-table.component.ts

when navigating to a note ID that is not found, Sentry still picked up errors before the app correctly navigates to the 404 page. Preventing init if no entity is defined now.

fix: avoid errors while re-routing for not-found notes

---

src/app/features/reporting/report-config.ts
src/app/features/reporting/reporting/reporting.component.spec.ts

to keep config simple for admins
- closes #3157

fix: remove unnecessary default values in ReportConfig entity

---

.browserslistrc
tsconfig.json

Based on the [discussion in #3175](https://github.com/Aam-Digital/ndb-core/pull/3175#discussion_r2242332558) I clarified the current state of browser support and browser targeting. We can change this in the future but I found it useful to have the current state documented.
* Update `.browserlistsrc` to the currently used browsers
* Update the `lib` setting in `tsconfig.json` to ES2023. All supported browsers [support ES2023](https://caniuse.com/?search=ES2023) (except for [WeakMap with non-registered keys](https://caniuse.com/mdn-javascript_builtins_weakmap_symbol_as_keys))
* Make it clear that no polyfills are used
* Define a sensible policy for updating `lib` to a newer version that considers that no polyfills are used at the moment.

chore: Clarify current state of browser support
